### ISSUE TITLE
Arch Support and AUR installation

### ISSUE THREAD

**Issue by furkan-kucuk** [RadeonOpenCompute/ROCm#615] opened 2018-11-18 11:01 UTC
Hi.

Arch Linux based distros, like Manjaro, are providing more newbie-friendly distro management systems like easy installation with aur repository, kernel and driver management softwares and etc. 

Since, for newbie users, it is a REAL pain to use our AMD hardwares on hardware accelerated libraries like PyTorch or tensorflow, and there is no proper documentation around on how to use it, it might be quite helpful to provide rocm stack on aur repository or as a driver which can be installed with Manjaro's driver management software.

**Comment by jlgreathouse** [comment] 2018-11-18 16:16
Dupe of #294

**Closed by jlgreathouse** 2018-11-18 16:16 UTC

**Comment by acxz** [comment] 2020-02-29 01:30
I know this is some time ago, but I just want to put this here in case others come across it. The ArchLinux community including me and some other folks have started picking up development on getting the ROCm stack working here: https://github.com/rocm-arch/rocm-arch. Feel free to submit PRs or issues!
