### ISSUE TITLE
Incorrect reported voltage after --gpureset

### ISSUE THREAD

**Issue by izixxxc** [RadeonOpenCompute/ROCm#1116] opened 2020-05-23 16:40 UTC
ROCm v3.3.0
Ubuntu 18.04
Radeon VII

:~$ rocm-smi --showvoltage

GPU[0] 		: Voltage (mV): 737

:~$ rocm-smi -d0 --gpureset

GPU[0] 		: GPU reset was successful

:~$ rocm-smi --showvoltage

GPU[0] 		: Voltage (mV): 1550

Power consumption is also misreported. Any quick fix?

**Comment by ROCmSupport** [comment] 2021-03-03 05:55
Thanks @izixxxc for reaching out.
I will check this for you.

**Comment by ROCmSupport** [comment] 2021-03-03 09:20
Hi @izixxxc 
I am able to reproduce this issue with the latest ROCm 4.0 also.
Looks like SMI is showing wrong result. let me debug more and get back to you on this.
Thank you.

**Comment by ROCmSupport** [comment] 2021-06-02 12:22
Hi @izixxxc 
Got update.
I debugged it and found that issue is not with SMI.
Actual problem is with kernel. Without SMI also, issue is observed.
And the issue is specific to Radeon7 only.

**Comment by ROCmSupport** [comment] 2021-06-02 12:23
Assigned to dev and fix ready, which is good news.
Most likely it will be part of ROCm 4.4, please stay tuned.
Thank you.

**Comment by ROCmSupport** [comment] 2021-08-04 10:09
Good news.
Issue is fixed with 4.3.
I just verified with 4.3 and issue is not observed anymore.

======================= ROCm System Management Interface =======================
=============================== Current voltage ================================
GPU[0]          : Voltage (mV): 737
GPU[1]          : Voltage (mV): 737
================================================================================
============================= End of ROCm SMI Log ==============================
taccuser@taccuser-SYS-4028GR-TR2:/usr/bin$ /opt/rocm/bin/roci -d0 --gpureset
-bash: /opt/rocm/bin/roci: No such file or directory
taccuser@taccuser-SYS-4028GR-TR2:/usr/bin$ /opt/rocm/bin/rocm-smi -d0 --gpureset
[sudo] password for taccuser:


======================= ROCm System Management Interface =======================
================================== Reset GPU ===================================
GPU[0]          : Successfully reset GPU 0
================================================================================
taccuser@taccuser-SYS-4028GR-TR2:/usr/bin$ /opt/rocm/bin/rocm-smi --showvoltage


======================= ROCm System Management Interface =======================
=============================== Current voltage ================================
GPU[0]          : Voltage (mV): 737
GPU[1]          : Voltage (mV): 737
================================================================================
============================= End of ROCm SMI Log ==============================

**Closed by ROCmSupport** 2021-08-04 10:09 UTC
