### ISSUE TITLE
ROCm 3.1 OpenCL bad compilation

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1039] opened 2020-03-10 01:57 UTC
ROCm 3.1 OpenCL, Linux kernel 5.4.24, RadeonVII

This issue refers to this commit:
https://github.com/preda/gpuowl/commit/79ae868be3fa0f97eaa11a762d1a4bcf2926fb82

To repro, please create dump folders named e.g. "good" and "bad", and run:

./gpuowl -prp 94080289 -dump good
./gpuowl -prp 94080289 -dump bad -use ENABLE_ROCM_BUG

The only difference between the two is controlled by the define ENABLE_ROCM_BUG in gpuowl.cl (see the commit linked above), i.e.:
```
#if ENABLE_ROCM_BUG
  out += MIDDLE * (WIDTH * SIZEX * gx + WG * gy);
#else
  out += MIDDLE * WIDTH * SIZEX * gx + MIDDLE * WG * gy;
#endif
```

In the repro case above, those values are:
```
MIDDLE = 10
WIDTH = 1024
SIZEX = 32
WG = 256
```
(in particular, there should be no overflow on the additions or multiplications).

In this situation, the two expressions used in the two branches
```
MIDDLE * (WIDTH * SIZEX * gx + WG * gy);
MIDDLE * WIDTH * SIZEX * gx + MIDDLE * WG * gy;
```
should be equivalent. Yet one works and the other doesn't.

What's more, if in the "bad" case we enable "DEBUG" which consists in just sprinkling a few printf() in the code (that are not even executed), the "bad" case starts working, see e.g.:
./gpuowl -prp 94080289 -use ENABLE_ROCM_BUG,DEBUG

The bug is isolated to a single kernel "fftMiddleOut", this should make it easier to localize.

As this bug at first look seems to concern a bad compilation of simple arithmetic on a pointer, it seems rather severe (i.e. high priority) to me.

**Comment by preda** [comment] 2020-03-10 12:32
The above problem does not reproduce on ROCm 2.10

**Comment by b-sumner** [comment] 2020-03-10 15:15
@preda do you have a unit test for fftMiddleOut?  How were you able to localize the problem?

Printf has a pretty big impact on the IR.  Have you tried cutting back on the optimization to see if that has an effect?  E.g. -O1, -O1, -O2?

**Comment by preda** [comment] 2020-03-10 22:09
@b-sumner I don't have a unit test (that executes only this kernel in isolation), that role is played by executing the program as instructed above -- it automatically detects whether the computation is correct or not ("self-validating"). Running
./gpuowl -prp 94080289 -use ENABLE_ROCM_BUG
on ROCm 3.1 will stop with an error message, but will proceed correctly on ROCm 2.10 or when run without the define. The problem is easy to reproduce, and it reproduces consistently and fast.

The behaviour with printf is just additional information; printf is not at the core of this issue which can be reproduced without any printf involvement.

Normally I compile without any -O, using the (OpenCL) default. I tried now with -O0 and the problem is still present.

I localized the problem in two ways: first, the define that switches on/off the bug is very small and localized, so the problem is linked to that change. Second, by doing diffs on the ISA dumps that are obtained with -dump as above, the ISA changes affect only that kernel (as expected based on the source changes).

IMO this could be a starting point to investigate this: compare the good ISA output with the bad one, and try to understand what is wrong there, next look for the cause of the difference.

**Comment by ROCmSupport** [comment] 2021-04-19 12:46
Hi @preda 
Thanks for reaching out.
Can you please check on ROCm 4.1 and share an update asap.
Thank you.

**Comment by preda** [comment] 2021-05-09 20:03
@ROCmSupport maybe fixed, feel free to close as it concerns a rather old ROCm version.

**Comment by ROCmSupport** [comment] 2021-05-10 04:17
Thanks @preda 
Closing this as the issue is fixed and no more observed with the latest ROCm 4.1 hopefully.
Thank you.

**Closed by ROCmSupport** 2021-05-10 04:17 UTC
