### ISSUE TITLE
ROCclr build issue, make failed.

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCm#1358] opened 2021-01-12 07:14 UTC
I filed this bug here since there seems no ROCclr project on its own.
I downloaded source for 4.0.0 but ROCclr build problem.

I built and installed llvm, ROCm-Compiler-support and ROCm-device-libs ok as prereq.

But build instruction for ROCclr as follows:

### Set the environment variables

```bash
export ROCclr_DIR="$(readlink -f ROCclr)"
export OPENCL_DIR="$(readlink -f ROCm-OpenCL-Runtime)"
```

### Build ROCclr
Here is command to build ROCclr:

```bash
cd "$ROCclr_DIR"
mkdir -p build; cd build
cmake -DOPENCL_DIR="$OPENCL_DIR" -DCMAKE_INSTALL_PREFIX=/opt/rocm/rocclr ..
make -j$(nproc)
```

It appears settings OPENCL_DIR is necessary.  So i set the env variable and make sure it is ok (below).
But "make" command after cmake resulted in following error:

oot@sriov-guest:~/ROCm/ROCclr/build# env | grep ROCclr
OPENCL_DIR=/root/ROCm/ROCclr/build/ROCm-OpenCL-Runtime
OLDPWD=/root/ROCm/ROCclr
PWD=/root/ROCm/ROCclr/build
ROCclr_DIR=/root/ROCm/ROCclr/build/ROCclr

"root@sriov-guest:~/ROCm/ROCclr/build# make
[  2%] Building CXX object device/rocm/CMakeFiles/oclrocm.dir/roccounters.cpp.o
In file included from /root/ROCm/ROCclr/device/rocm/roccounters.hpp:24:0,
                 from /root/ROCm/ROCclr/device/rocm/roccounters.cpp:21:
/root/ROCm/ROCclr/include/top.hpp:36:10: fatal error: CL/opencl.h: No such file or directory
 #include "CL/opencl.h"
          ^~~~~~~~~~~~~
compilation terminated.
device/rocm/CMakeFiles/oclrocm.dir/build.make:62: recipe for target 'device/rocm/CMakeFiles/oclrocm.dir/roccounters.cpp.o' failed
make[2]: *** [device/rocm/CMakeFiles/oclrocm.dir/roccounters.cpp.o] Error 1
CMakeFiles/Makefile2:122: recipe for target 'device/rocm/CMakeFiles/oclrocm.dir/all' failed
make[1]: *** [device/rocm/CMakeFiles/oclrocm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
"

I dont think building ROCm-OpenCL-Runtime is prereq because 1. it does not say so in the ROCclr's readme and ROCm-OpenCL-Runtime build readme specified ROCclr build is a prereq.

**Comment by xuhuisheng** [comment] 2021-01-12 07:21
`git clone https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime`
and set its dir to OPENCL_DIR

**Comment by ROCmSupport** [comment] 2021-01-12 07:23
Thanks @gggh000 for reaching us.
Request you to install/use OpenCL RT path to solve the issue.

**Comment by ROCmSupport** [comment] 2021-01-12 07:53
And also, we are working on providing proper build instructions for complete ROCm. Please track #1188

**Comment by gggh000** [comment] 2021-01-12 18:47
> `git clone https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime`
> and set its dir to OPENCL_DIR

I dont see why it would work. I already pointed to existing directory which downloaded the source.

**Comment by gggh000** [comment] 2021-01-12 18:47
> Request you to install/use OpenCL RT path to solve the issue.

How do i do that? I dont know what OpenCL RT and how to get it and install.

**Comment by xuhuisheng** [comment] 2021-01-15 08:36
My environment is Ubuntu-20.04.1

**cmake**

```
work@00923371e74e:~/ROCm/ROCclr/build$ cmake -DOPENCL_DIR="$OPENCL_DIR" -DCMAKE_INSTALL_PREFIX=/opt/rocm/rocclr ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Code Object Manager found at /opt/rocm/lib/cmake/amd_comgr.
-- HSA Runtime found at /opt/rocm/lib/cmake/hsa-runtime64.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found: /usr/lib/x86_64-linux-gnu/libnuma.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/work/ROCm/ROCclr/build

```

then **make**

```
work@00923371e74e:~/ROCm/ROCclr/build$ make
Scanning dependencies of target oclrocm
[  2%] Building CXX object device/rocm/CMakeFiles/oclrocm.dir/roccounters.cpp.o
[  4%] Building CXX object device/rocm/CMakeFiles/oclrocm.dir/rocprintf.cpp.o

```

**Comment by ROCmSupport** [comment] 2021-01-18 09:26
@gggh000,
     I hope the issue is resolved with the suggested package.
     kindly let us know if you are still facing this problem.

**Comment by ROCmSupport** [comment] 2021-01-27 07:15
Hi @gggh000 
Please share an update on the issue. Will close it, if you are not able to reproduce anymore.
Thank you.

**Comment by ROCmSupport** [comment] 2021-02-08 10:14
Hi @gggh000 
Closing this as there is no response from you for the last 3 to 4 weeks.
Assuming that issue is resolved.
Request you to open a new issue, if you find any.
Thank you.

**Closed by ROCmSupport** 2021-02-08 10:14 UTC
