### ISSUE TITLE
OpenCL discrepency (ROCm 1.6-115 vs Catalyst)

### ISSUE THREAD

**Issue by newling** [RadeonOpenCompute/ROCm#178] opened 2017-08-07 09:40 UTC
MIOpenGEMM generates OpenCL kernels based on ~20 hyper-parameters. Almost all of generated kernels compile and give correct results on ROCm. But occasionally a combination of hyper-parameters will give a  kernel which either

(1) gives incorrect results on ROCm, but correct on Catalyst. An example is here
https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/blob/develop/rocm1/incorrect1.cpp

(2) hangs in clBuildProgram on ROCm, but compiles fine on Catalyst. An example is here 
https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/blob/develop/rocm1/hangs1.cpp

I can't pinpoint the problem, it seems to arise from a complex interaction of hyper-parameters. 
Not sure what info I can provide?

**Comment by gstoner** [comment] 2017-08-09 21:22
Are you sure you do not have out of bounds memory references,  Catalyst would just let them though.

**Comment by newling** [comment] 2017-08-09 21:53
i'm pretty certain there are no out of bound mem refs here.

**Comment by searlmc1** [comment] 2017-08-22 00:31
I can reproduce the issue:
$ /usr/bin/c++ -I/opt/rocm/opencl/include incorrect1.cpp -std=c++11 -L/opt/rocm/opencl/lib/x86_64/ -lOpenCL
$ a.out
clCreateCommandQueue..clCreateProgramWithSource..clBuildProgram..clSetKernelArg(s)..clEnqueueNDRangeKernel..clFinish..clEnqueueReadBuffer..clFinish..done.
sum of initial c = 154.0970916748046875
sum of final c  gpu = 132.538177490234375
sum of final on cpu = 20.899591445922851562
(cpu - gpu )/cpu = -111.638588
elapsed seconds : 0.004344373941

Passes with -cl-opt-disable:
$ export AMD_OCL_BUILD_OPTIONS_APPEND="-cl-opt-disable"
$ a.out
clCreateCommandQueue..clCreateProgramWithSource..clBuildProgram..clSetKernelArg(s)..clEnqueueNDRangeKernel..clFinish..clEnqueueReadBuffer..clFinish..done.
sum of initial c = 154.0970916748046875
sum of final c  gpu = 20.899591445922851562
sum of final on cpu = 20.899591445922851562
(cpu - gpu )/cpu = 0
elapsed seconds : 0.006285465788

I’ll continue investigating; thanks for reporting.

**Comment by dagamayank** [comment] 2017-09-05 21:28
@searlmc1 Any progress on this bug?

cc/ @acmeman925

**Comment by searlmc1** [comment] 2017-09-05 21:48
@dagamayank ,

Progress of sorts: I’ve been working with incorrect1.cpp; it appears to be a codegen issue triggered by loop unrolling; AMD_OCL_BUILD_OPTIONS_APPEND=”-Wf,-fno-unroll-loops" cures the bug; adding “#pragma unroll 1“ to the loops helped to narrow it to a particular loop, but it is a bit touchy. I.e., it looks like a combination of loops need to be unrolled to trigger the bad codegen. Still working to identify the root problem.

cc/ @acmeman925

**Comment by dagamayank** [comment] 2017-10-04 15:02
@searlmc1 Any progress on this bug? We are seeing this issue crop up in a lot of other tests. We are spending a lot of time debugging them to ultimately figure out it is a compiler bug.

I checked the 1460579 build as well which is fairly recent and this bug persists there as well.

**Comment by searlmc1** [comment] 2017-10-04 15:11
@dagamayank  - no additional progress; sorry for the delay; I'll spend more time on it.

**Comment by dagamayank** [comment] 2017-11-21 22:44
@searlmc1 Any update on this issue? We are now hitting the same bug on our RNN tests also.

**Comment by searlmc1** [comment] 2017-12-29 00:44
Appears to be a problem in the load/store optimizer; possibly triggered by this commit:
commit 881e9f317759f2a1e32a01bad39eb08cdad91dc1
Author: Stanislav Mekhanoshin <Stanislav.Mekhanoshin@amd.com>
Date:   Thu Apr 13 17:53:07 2017 +0000

    [AMDGPU] Combine DS operations with offsets bigger than byte

    In many cases ds operations can be combined even if offsets do not
    fit into 8 bit encoding. What it takes is to adjust base address.

    Differential Revision: https://reviews.llvm.org/D31993

    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@300227 91177308-0d34-0410-b5e6-96231b3b80d8

**Comment by acmeman925** [comment] 2018-02-15 23:04
@searlmc1  Could log this in Jira and assign to Stas

**Comment by searlmc1** [comment] 2018-02-15 23:10
The issue was logged into jira and has been fixed ( https://reviews.llvm.org/rL323153 ).

**Comment by searlmc1** [comment] 2018-02-16 16:22
This was a compiler issue and has been fixed, so closing.

**Closed by searlmc1** 2018-02-16 16:22 UTC
Labels: Bug_Functional_Issue
