### ISSUE TITLE
HIP4.1 make filed

### ISSUE THREAD

**Issue by SomnusMistletoe** [RadeonOpenCompute/ROCm#1459] opened 2021-04-24 09:07 UTC
Hi @ROCmSupport 
I have install rocm-dkms 4.1.0 and llvm-project, ROCm-Device-Libs, ROCclr successfully.
when I
git clone -b rocm-4.1.x https://github.com/ROCm-Developer-Tools/HIP.git
and continue to make HIP, I get the following error:

```
# make -j
Scanning dependencies of target gen-prof-api-str-header
[  0%] Generating profiling primitives: /usr/local/HIP/build/include/hip/hcc_detail/hip_prof_str.h
api: hip_init - hip_impl
api: hipInit
api: hipDriverGetVersion
api: hipRuntimeGetVersion
api: hipDeviceGet
api: hipDeviceComputeCapability
api: hipDeviceGetName
api: hipDeviceGetP2PAttribute
api: hipDeviceGetPCIBusId
api: hipDeviceGetByPCIBusId
api: hipDeviceTotalMem
api: hipDeviceSynchronize
api: hipDeviceReset
api: hipSetDevice
api: hipGetDevice
api: hipGetDeviceCount
api: hipDeviceGetAttribute
api: hipGetDeviceProperties
api: hipDeviceSetCacheConfig
api: hipDeviceGetCacheConfig
api: hipDeviceGetLimit
api: hipDeviceGetSharedMemConfig
api: hipGetDeviceFlags
api: hipDeviceSetSharedMemConfig
api: hipSetDeviceFlags
api: hipChooseDevice
api: hipExtGetLinkTypeAndHopCount
api: hipIpcGetMemHandle
api: hipIpcOpenMemHandle
api: hipIpcCloseMemHandle
api: hipIpcGetEventHandle
api: hipIpcOpenEventHandle
api: hipFuncSetAttribute
api: hipFuncSetCacheConfig
api: hipFuncSetSharedMemConfig
api: hipGetLastError
api: hipPeekAtLastError
api: hipGetErrorName
api: hipGetErrorString
api: hipStreamCreate
api: hipStreamCreateWithFlags
api: hipStreamCreateWithPriority
api: hipDeviceGetStreamPriorityRange
api: hipStreamDestroy
api: hipStreamQuery
api: hipStreamSynchronize
api: hipStreamWaitEvent
api: hipStreamGetFlags
api: hipStreamGetPriority
api: hipExtStreamCreateWithCUMask
api: hipExtStreamGetCUMask
api: hipStreamAddCallback
api: hipEventCreateWithFlags
api: hipEventCreate
api: hipEventRecord
api: hipEventRecord
api: hipEventDestroy
api: hipEventSynchronize
api: hipEventElapsedTime
api: hipEventQuery
api: hipPointerGetAttributes
api: hipMalloc
api: hipExtMallocWithFlags
api: hipMallocHost
api: hipMemAllocHost
api: hipHostMalloc
api: hipMallocManaged
api: hipMemPrefetchAsync
api: hipMemAdvise
api: hipMemRangeGetAttribute
api: hipMemRangeGetAttributes
api: hipStreamAttachMemAsync
api: hipHostAlloc
api: hipHostGetDevicePointer
api: hipHostGetFlags
api: hipHostRegister
api: hipHostUnregister
api: hipMallocPitch
api: hipMemAllocPitch
api: hipFree
api: hipFreeHost
api: hipHostFree
api: hipMemcpy
api: hipMemcpyWithStream
api: hipMemcpyHtoD
api: hipMemcpyDtoH
api: hipMemcpyDtoD
api: hipMemcpyHtoDAsync
api: hipMemcpyDtoHAsync
api: hipMemcpyDtoDAsync
api: hipModuleGetGlobal
api: hipGetSymbolAddress
api: hipGetSymbolSize
api: hipMemcpyToSymbol
api: hipMemcpyToSymbolAsync
api: hipMemcpyFromSymbol
api: hipMemcpyFromSymbolAsync
api: hipModuleGetGlobal
api: read_agent_global_from_process - hidden
api: hipGetSymbolAddress - hidden
api: hipGetSymbolSize - hidden
api: hipMemcpyToSymbol - hip_impl
api: hipMemcpyToSymbol - hidden
api: hipMemcpyToSymbolAsync - hip_impl
api: hipMemcpyFromSymbol - hip_impl
api: hipMemcpyFromSymbolAsync - hip_impl
api: hipMemcpyToSymbolAsync - hidden
api: hipMemcpyFromSymbol - hidden
api: hipMemcpyFromSymbolAsync - hidden
api: hipMemcpyAsync
api: hipMemset
api: hipMemsetD8
api: hipMemsetD8Async
api: hipMemsetD16
api: hipMemsetD16Async
api: hipMemsetD32
api: hipMemsetAsync
api: hipMemsetD32Async
api: hipMemset2D
api: hipMemset2DAsync
api: hipMemset3D
api: hipMemset3DAsync
api: hipMemGetInfo
api: hipMemPtrGetInfo
api: hipMallocArray
api: hipArrayCreate
api: hipArray3DCreate
api: hipMalloc3D
api: hipFreeArray
api: hipFreeMipmappedArray
api: hipMalloc3DArray
api: hipMallocMipmappedArray
api: hipGetMipmappedArrayLevel
api: hipMemcpy2D
api: hipMemcpyParam2D
api: hipMemcpyParam2DAsync
api: hipMemcpy2DAsync
api: hipMemcpy2DToArray
api: hipMemcpyToArray
api: hipMemcpyFromArray
api: hipMemcpy2DFromArray
api: hipMemcpy2DFromArrayAsync
api: hipMemcpyAtoH
api: hipMemcpyHtoA
api: hipMemcpy3D
api: hipMemcpy3DAsync
api: hipDrvMemcpy3D
api: hipDrvMemcpy3DAsync
api: hipDeviceCanAccessPeer
api: hipDeviceEnablePeerAccess
api: hipDeviceDisablePeerAccess
api: hipMemGetAddressRange
api: hipMemcpyPeer
api: hipMemcpyPeerAsync
api: hipCtxCreate
api: hipCtxDestroy
api: hipCtxPopCurrent
api: hipCtxPushCurrent
api: hipCtxSetCurrent
api: hipCtxGetCurrent
api: hipCtxGetDevice
api: hipCtxGetApiVersion
api: hipCtxGetCacheConfig
api: hipCtxSetCacheConfig
api: hipCtxSetSharedMemConfig
api: hipCtxGetSharedMemConfig
api: hipCtxSynchronize
api: hipCtxGetFlags
api: hipCtxEnablePeerAccess
api: hipCtxDisablePeerAccess
api: hipDevicePrimaryCtxGetState
api: hipDevicePrimaryCtxRelease
api: hipDevicePrimaryCtxRetain
api: hipDevicePrimaryCtxReset
api: hipDevicePrimaryCtxSetFlags
api: hipModuleLoad
api: hipModuleUnload
api: hipModuleGetFunction
api: hipFuncGetAttributes
api: hipFuncGetAttribute
api: hipModuleGetGlobal
api: hipModuleGetTexRef
api: hipModuleLoadData
api: hipModuleLoadDataEx
api: hipModuleLaunchKernel
api: hipLaunchCooperativeKernel
api: hipLaunchCooperativeKernelMultiDevice
api: hipExtLaunchMultiKernelMultiDevice
api: hipModuleOccupancyMaxPotentialBlockSize
api: hipModuleOccupancyMaxPotentialBlockSizeWithFlags
api: hipModuleOccupancyMaxActiveBlocksPerMultiprocessor
api: hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
api: hipOccupancyMaxActiveBlocksPerMultiprocessor
api: hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
api: hipOccupancyMaxPotentialBlockSize
api: hipProfilerStart
api: hipProfilerStop
api: hipConfigureCall
api: hipSetupArgument
api: hipLaunchByPtr
api: __hipPushCallConfiguration
api: __hipPopCallConfiguration
api: hipLaunchKernel
api: hipExtLaunchKernel
api: hipBindTexture
Parsing /usr/local/HIP/rocclr for '\.cpp$'
/usr/local/HIP/rocclr/hip_stream.cpp
	hipStreamCreateWithFlags
	hipStreamCreate
	hipStreamCreateWithPriority
	hipDeviceGetStreamPriorityRange
	hipStreamGetFlags
	hipStreamSynchronize
	hipStreamDestroy
	hipStreamWaitEvent
	hipStreamQuery
	hipStreamAddCallback
	hipExtStreamCreateWithCUMask
	hipStreamGetPriority
	hipExtStreamGetCUMask
/usr/local/HIP/rocclr/cl_lqdflash_amd.cpp
/usr/local/HIP/rocclr/hip_error.cpp
	hipGetLastError
	hipPeekAtLastError
/usr/local/HIP/rocclr/fixme.cpp
/usr/local/HIP/rocclr/hip_texture.cpp
/usr/local/HIP/rocclr/hip_intercept.cpp
/usr/local/HIP/rocclr/hip_global.cpp
/usr/local/HIP/rocclr/hip_event.cpp
	hipEventCreateWithFlags
	hipEventCreate
	hipEventDestroy
	hipEventElapsedTime
	hipEventRecord
	hipEventSynchronize
	hipEventQuery
/usr/local/HIP/rocclr/hip_activity.cpp
/usr/local/HIP/rocclr/hip_rtc.cpp
/usr/local/HIP/rocclr/hip_device.cpp
	hipDeviceGet
	hipDeviceTotalMem
	hipDeviceComputeCapability
	hipDeviceGetName
	hipGetDeviceProperties
/usr/local/HIP/rocclr/hip_module.cpp
	hipModuleUnload
	hipModuleLoad
	hipModuleLoadData
	hipModuleLoadDataEx
	hipModuleGetFunction
	hipModuleGetGlobal
	hipFuncGetAttribute
	hipFuncGetAttributes
	hipFuncSetAttribute
	hipFuncSetCacheConfig
	hipFuncSetSharedMemConfig
	hipModuleLaunchKernel
	hipExtModuleLaunchKernel
	hipHccModuleLaunchKernel
	hipLaunchKernel
	hipExtLaunchKernel
	hipLaunchCooperativeKernel
	hipLaunchCooperativeKernelMultiDevice
	hipExtLaunchMultiKernelMultiDevice
	hipModuleGetTexRef
/usr/local/HIP/rocclr/hip_context.cpp
	hipInit
	hipCtxCreate
	hipCtxSetCurrent
	hipCtxGetCurrent
	hipCtxGetSharedMemConfig
	hipRuntimeGetVersion
	hipCtxDestroy
	hipCtxPopCurrent
	hipCtxPushCurrent
	hipDriverGetVersion
	hipCtxGetDevice
	hipCtxGetApiVersion
	hipCtxGetCacheConfig
	hipCtxSetCacheConfig
	hipCtxSetSharedMemConfig
	hipCtxSynchronize
	hipCtxGetFlags
	hipDevicePrimaryCtxGetState
	hipDevicePrimaryCtxRelease
	hipDevicePrimaryCtxRetain
	hipDevicePrimaryCtxReset
	hipDevicePrimaryCtxSetFlags
/usr/local/HIP/rocclr/hip_code_object.cpp
/usr/local/HIP/rocclr/hip_device_runtime.cpp
	hipChooseDevice
	hipDeviceGetAttribute
	hipDeviceGetByPCIBusId
	hipDeviceGetCacheConfig
	hipDeviceGetLimit
	hipDeviceGetPCIBusId
	hipDeviceGetSharedMemConfig
	hipDeviceReset
	hipDeviceSetCacheConfig
	hipDeviceSetSharedMemConfig
	hipDeviceSynchronize
	hipGetDevice
	hipGetDeviceCount
	hipGetDeviceFlags
	hipIpcGetEventHandle
	hipIpcOpenEventHandle
	hipSetDevice
	hipSetDeviceFlags
/usr/local/HIP/rocclr/hip_fatbin.cpp
/usr/local/HIP/rocclr/cl_gl.cpp
/usr/local/HIP/rocclr/hip_platform.cpp
	hipConfigureCall
	__hipPushCallConfiguration
	__hipPopCallConfiguration
	hipSetupArgument
	hipLaunchByPtr
	hipGetSymbolAddress
	hipGetSymbolSize
	hipOccupancyMaxPotentialBlockSize
	hipModuleOccupancyMaxPotentialBlockSize
	hipModuleOccupancyMaxPotentialBlockSizeWithFlags
	hipModuleOccupancyMaxActiveBlocksPerMultiprocessor
	hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
	hipOccupancyMaxActiveBlocksPerMultiprocessor
	hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
/usr/local/HIP/rocclr/hip_peer.cpp
	hipDeviceCanAccessPeer args mismatch:
		/usr/local/HIP/rocclr/hip_peer.cpp line(24)
		api: int*, hipCtx_t, hipCtx_t, 
		eta: int*, int, int, 

	hipMemcpyPeer args mismatch:
		/usr/local/HIP/rocclr/hip_peer.cpp line(33)
		api: void*, hipCtx_t, const void*, hipCtx_t, size_t, 
		eta: void*, int, const void*, int, size_t, 

	hipMemcpyPeerAsync args mismatch:
		/usr/local/HIP/rocclr/hip_peer.cpp line(42)
		api: void*, hipCtx_t, const void*, hipCtx_t, size_t, hipStream_t, 
		eta: void*, int, const void*, int, size_t, hipStream_t, 

	hipExtGetLinkTypeAndHopCount
	hipDeviceGetP2PAttribute
	hipDeviceCanAccessPeer
	hipDeviceDisablePeerAccess
	hipDeviceEnablePeerAccess
	hipMemcpyPeer
	hipMemcpyPeerAsync
	hipCtxEnablePeerAccess
	hipCtxDisablePeerAccess
/usr/local/HIP/rocclr/hip_surface.cpp
/usr/local/HIP/rocclr/hip_hmm.cpp
	hipMallocManaged
	hipMemPrefetchAsync
	hipMemAdvise
	hipMemRangeGetAttribute
	hipMemRangeGetAttributes
	hipStreamAttachMemAsync
/usr/local/HIP/rocclr/hip_memory.cpp
	hipExtMallocWithFlags
	hipMalloc
	hipHostMalloc
	hipFree
	hipMemcpy
	hipMemcpyWithStream
	hipMemPtrGetInfo
	hipHostFree
	hipFreeArray
	hipMemGetAddressRange
	hipMemGetInfo
	hipMallocPitch
	hipMalloc3D
	hipArrayCreate
	hipMallocArray
	hipArray3DCreate
	hipMalloc3DArray
	hipHostGetFlags
	hipHostRegister
	hipHostUnregister
	hipHostAlloc
	hipMemcpyToSymbol
	hipMemcpyFromSymbol
	hipMemcpyToSymbolAsync
	hipMemcpyFromSymbolAsync
	hipMemcpyHtoD
	hipMemcpyDtoH
	hipMemcpyDtoD
	hipMemcpyAsync
	hipMemcpyHtoDAsync
	hipMemcpyDtoDAsync
	hipMemcpyDtoHAsync
	hipMemcpyParam2D
	hipMemcpy2D
	hipMemcpy2DAsync
	hipMemcpy2DToArray
	hipMemcpyToArray
	hipMemcpyFromArray
	hipMemcpyHtoA
	hipMemcpyAtoH
	hipMemcpy3D
	hipMemcpy3DAsync
	hipDrvMemcpy3D
	hipDrvMemcpy3DAsync
	hipMemset
	hipMemsetAsync
	hipMemsetD8
	hipMemsetD8Async
	hipMemsetD16
	hipMemsetD16Async
	hipMemsetD32
	hipMemsetD32Async
	hipMemset2D
	hipMemset2DAsync
	hipMemset3D
	hipMemset3DAsync
	hipMemAllocPitch
	hipMemAllocHost
	hipIpcGetMemHandle
	hipIpcOpenMemHandle
	hipIpcCloseMemHandle
	hipHostGetDevicePointer
	hipPointerGetAttributes
	hipMemcpyParam2DAsync
	hipMemcpy2DFromArray
	hipMemcpy2DFromArrayAsync
	hipMallocMipmappedArray
	hipFreeMipmappedArray
	hipGetMipmappedArrayLevel
	hipMallocHost
	hipFreeHost
/usr/local/HIP/rocclr/hip_profile.cpp
	hipProfilerStart
	hipProfilerStop
Init missing: hipKernelNameRef
 Warning: implementation not found: hipGetErrorName
/usr/local/HIP/rocclr/hip_prof_gen.py Warning: implementation not found: hipGetErrorName
 Warning: implementation not found: hipGetErrorString
/usr/local/HIP/rocclr/hip_prof_gen.py Warning: implementation not found: hipGetErrorString
 Warning: 2 API calls missing in interception layer
/usr/local/HIP/rocclr/hip_prof_gen.py Warning: 2 API calls missing in interception layer
Private: hipCreateTextureObject
Private: hipDestroyTextureObject
Private: hipGetTextureObjectResourceDesc
Private: hipGetTextureObjectResourceViewDesc
Private: hipGetTextureObjectTextureDesc
Private: hipBindTexture2D
Private: hipBindTextureToArray
Private: hipBindTextureToMipmappedArray
Private: hipUnbindTexture
Private: hipBindTexture
Private: hipGetChannelDesc
Private: hipGetTextureAlignmentOffset
Private: hipGetTextureReference
Private: hipTexRefSetFormat
Private: hipTexRefSetFlags
Private: hipTexRefSetFilterMode
Private: hipTexRefGetAddressMode
Private: hipTexRefSetAddressMode
Private: hipTexRefGetArray
Private: hipTexRefSetArray
Private: hipTexRefGetAddress
Private: hipTexRefSetAddress
Private: hipTexRefSetAddress2D
Private: hipTexRefGetBorderColor
Private: hipTexRefGetFilterMode
Private: hipTexRefGetFlags
Private: hipTexRefGetFormat
Private: hipTexRefGetMaxAnisotropy
Private: hipTexRefGetMipmapFilterMode
Private: hipTexRefGetMipmapLevelBias
Private: hipTexRefGetMipmapLevelClamp
Private: hipTexRefGetMipmappedArray
Private: hipTexRefSetBorderColor
Private: hipTexRefSetMaxAnisotropy
Private: hipTexRefSetMipmapFilterMode
Private: hipTexRefSetMipmapLevelBias
Private: hipTexRefSetMipmapLevelClamp
Private: hipTexRefSetMipmappedArray
Private: hipTexObjectCreate
Private: hipTexObjectDestroy
Private: hipTexObjectGetResourceDesc
Private: hipTexObjectGetResourceViewDesc
Private: hipTexObjectGetTextureDesc
Private: hipDeviceGetCount
Private: ihipModuleLaunchKernel
Private: hipModuleLaunchKernelExt
Private: hipSetValidDevices
Private: hipCreateSurfaceObject
Private: hipDestroySurfaceObject
Private: hipArrayDestroy
Private: hipArray3DGetDescriptor
Private: hipArrayGetDescriptor
Private: hipMemcpy2DArrayToArray
Private: hipMemcpyArrayToArray
Private: hipMemcpyFromArrayAsync
Private: hipMemcpy2DToArrayAsync
Private: hipMemcpyToArrayAsync
Private: hipMemcpyAtoA
Private: hipMemcpyAtoD
Private: hipMemcpyAtoHAsync
Private: hipMemcpyDtoA
Private: hipMemcpyHtoAAsync
Private: hipMipmappedArrayCreate
Private: hipMipmappedArrayDestroy
Private: hipMipmappedArrayGetLevel
[  0%] Built target gen-prof-api-str-header
Scanning dependencies of target hip64
[  0%] Building CXX object rocclr/CMakeFiles/hip64.dir/hip_context.cpp.o
In file included from /usr/local/HIP/rocclr/hip_platform.hpp:23,
                 from /usr/local/HIP/rocclr/hip_context.cpp:23:
/usr/local/HIP/rocclr/hip_fatbin.hpp:49:61: error: macro "guarantee" passed 2 arguments, but takes just 1
   49 |     guarantee(device_id >= 0, "Invalid DeviceId less than 0");
      |                                                             ^
In file included from /usr/local/ROCclr/include/top.hpp:101,
                 from /usr/local/ROCclr/include/vdi_common.hpp:24,
                 from /usr/local/HIP/rocclr/hip_internal.hpp:24,
                 from /usr/local/HIP/rocclr/hip_context.cpp:22:
/usr/local/ROCclr/utils/debug.hpp:93: note: macro "guarantee" defined here
   93 | #define guarantee(cond)                                                                            \
      | 
In file included from /usr/local/HIP/rocclr/hip_platform.hpp:23,
                 from /usr/local/HIP/rocclr/hip_context.cpp:23:
/usr/local/HIP/rocclr/hip_fatbin.hpp:50:131: error: macro "guarantee" passed 2 arguments, but takes just 1
   50 |  "Invalid DeviceId, greater than no of fatbin device info!");
      |                                                            ^

In file included from /usr/local/ROCclr/include/top.hpp:101,
                 from /usr/local/ROCclr/include/vdi_common.hpp:24,
                 from /usr/local/HIP/rocclr/hip_internal.hpp:24,
                 from /usr/local/HIP/rocclr/hip_context.cpp:22:
/usr/local/ROCclr/utils/debug.hpp:93: note: macro "guarantee" defined here
   93 | #define guarantee(cond)                                                                            \
      | 
In file included from /usr/local/HIP/rocclr/hip_platform.hpp:25,
                 from /usr/local/HIP/rocclr/hip_context.cpp:23:
/usr/local/HIP/rocclr/hip_code_object.hpp:98:74: error: macro "guarantee" passed 2 arguments, but takes just 1
   98 |       guarantee(false, "Device mismatch from where this module is loaded");
      |                                                                          ^
In file included from /usr/local/ROCclr/include/top.hpp:101,
                 from /usr/local/ROCclr/include/vdi_common.hpp:24,
                 from /usr/local/HIP/rocclr/hip_internal.hpp:24,
                 from /usr/local/HIP/rocclr/hip_context.cpp:22:
/usr/local/ROCclr/utils/debug.hpp:93: note: macro "guarantee" defined here
   93 | #define guarantee(cond)                                                                            \
      | 
In file included from /usr/local/HIP/rocclr/hip_internal.hpp:25,
                 from /usr/local/HIP/rocclr/hip_context.cpp:22:
/usr/local/HIP/rocclr/hip_prof_api.h: In constructor ‘api_callbacks_table_t::api_callbacks_table_t()’:
/usr/local/HIP/rocclr/hip_prof_api.h:72:59: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct api_callbacks_table_t::hip_cb_table_t’ with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
   72 |      memset(&callbacks_table_, 0, sizeof(callbacks_table_));
      |                                                           ^
/usr/local/HIP/rocclr/hip_prof_api.h:67:10: note: ‘struct api_callbacks_table_t::hip_cb_table_t’ declared here
   67 |   struct hip_cb_table_t {
      |          ^~~~~~~~~~~~~~
In file included from /usr/local/HIP/rocclr/hip_platform.hpp:23,
                 from /usr/local/HIP/rocclr/hip_context.cpp:23:
/usr/local/HIP/rocclr/hip_fatbin.hpp: In member function ‘void hip::FatBinaryInfo::DeviceIdCheck(int) const’:
/usr/local/HIP/rocclr/hip_fatbin.hpp:49:5: error: ‘guarantee’ was not declared in this scope
   49 |     guarantee(device_id >= 0, "Invalid DeviceId less than 0");
      |     ^~~~~~~~~
In file included from /usr/local/HIP/rocclr/hip_platform.hpp:25,
                 from /usr/local/HIP/rocclr/hip_context.cpp:23:
/usr/local/HIP/rocclr/hip_code_object.hpp: In member function ‘void hip::DynCO::CheckDeviceIdMatch()’:
/usr/local/HIP/rocclr/hip_code_object.hpp:98:7: error: ‘guarantee’ was not declared in this scope
   98 |       guarantee(false, "Device mismatch from where this module is loaded");
      |       ^~~~~~~~~
make[2]: *** [rocclr/CMakeFiles/hip64.dir/build.make:63: rocclr/CMakeFiles/hip64.dir/hip_context.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:9439: rocclr/CMakeFiles/hip64.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
Best regards,
Thank you.

**Comment by ROCmSupport** [comment] 2021-04-26 02:41
Thanks @SomnusMistletoe for reaching out.
I will check this for you and get back asap.
Thank you.

**Comment by ROCmSupport** [comment] 2021-04-26 05:25
Thanks @SomnusMistletoe for reaching out.
Can you please share your config details like OS, asic, outputs of rocminfo, clinfo etc.,.
Thank you.

**Comment by SomnusMistletoe** [comment] 2021-04-26 06:03
Hi @ROCmSupport，
I solve this problem by changing a
git version and modifying some parameters in the CMakeLists，I'll close the problem soon.
Best regards,
Thank you.

**Comment by ROCmSupport** [comment] 2021-04-26 06:19
Thanks @SomnusMistletoe 
I am NOT able to reproduce the problem locally.
Thanks for confirming that issue is resolved by changing git version and modifying some parameters in the CMakeLists.
Thank you.

**Closed** 2021-04-26 09:21 UTC
