### ISSUE TITLE
rocm dkms on arch

### ISSUE THREAD

**Issue by ghost** [RadeonOpenCompute/ROCm#294] opened 2018-01-02 00:55 UTC
Dear ROCm Team.

I am trying creating a aur PKG on arch for ROCm. As your work is really great, the arch community should benefit from it. For a good start i took the dkms package you are providing for ubuntu.
http://repo.radeon.com/rocm/apt/debian/pool/main/r/rocm-utils/rocm-utils_1.7.60_amd64.deb

As i understood the dependecies are small it should be doable easy? All includes files are in the package allready, no crossdeps so far. 

So i extracted the sources and brought em /usr/share and /usr/src. 

dkms add -m rock -v 1.7.60

worked and dkms is linking the dkms conf and sources right. 
Stupid as i am the next i tried just build it, which obviously failed :) - (dkms autoinstall)

the dmks buildlog is here https://pastebin.com/UuNRsEXQ
It looks like some vars arent defined. Where is it done in your package so i can adjust it for arch.

Maybe one of the more expirienced ones here can point me into the right direction?

Cheers
derdigge

PS: sorry for my bad english

**Comment by Narthorn** [comment] 2018-01-14 09:14
You need to add arch as a build target in the Makefile, as in https://aur.archlinux.org/cgit/aur.git/tree/0003-add-archlinux-as-build-option.patch?h=amdgpu-pro-installer.

Unfortunately, that's not enough, as the rock-dkms package is only meant to compile against kernel versions up to 4.13, while arch uses 4.14 (soon 4.15). The package probably needs to be patched by the ROCm team or someone knowledgeable to make it build properly against 4.14 and 4.15.

**Comment by Ezzestus** [comment] 2018-01-18 07:24
I am also looking for incormation on this topic. Also would be willing to try and help/contribute to an aur PKGBUILD though I have not delved very deep into that aspect of arch.

**Comment by bradmccormack** [comment] 2018-01-18 12:27
@Narthorn It's probably worth patching the Kernel config as part of the package to apply CONFIG_KALLSYMS_ALL=y then install via DKMS.

Is that really all that is required?

I must admit, before I looked at this issue I downloaded the source and was looking at a directory structure like
```
atmi/               HIP/           ROCK-Kernel-Driver/  ROCT-Thunk-Interface/
compiler-rt/        HIP-Examples/  ROCm-Device-Libs/
hcc/                lld/           ROCR-Runtime/
hcc-clang-upgrade/  llvm/          ROC-smi/
```

I wasn't so sure about the distinction between ROCm-Device-Libs ROC-smi etc. Some of them I could obviously safely ignore but the others ... I wasn't so sure.

**Comment by Ezzestus** [comment] 2018-01-19 00:56
has anyone got a working PKGBUILD?

**Comment by Ezzestus** [comment] 2018-01-22 14:10
k so I decompress the .deb with `ar -x ocm-utils_1.7.60_amd64.deb` and I get three files. control.tar.gz, data.tar.gz and debian-binary. Then I decompress the data.tar.gz with `tar -xzf data.tar.gz` and I get an opt folder that contains a rocm folder taht contains nothing except .info. Am I missing Something?

**Comment by derdigge** [comment] 2018-01-22 14:26
Sorry for late reply, was on holiday. To be honest i didnt get it work. To much "patch arround".
For those are after "mining issues" i can confirm that Linux 4.14.14-1-ARCH works with grub param "amdgpu.vm_fragment_size=9" mining eth steady.

If one trying to continue this, it will become unmaintainable with archs rolling kernels. Patches will be become invalid every now and then. A static kernel could be used but thats not the arch way.

**Comment by 949f45ac** [comment] 2018-04-09 06:44
@Ezzestus The issue creator penned it slightly wrong. Sources for the dkms are provided by ubuntu package rock-dkms, direct download link is http://repo.radeon.com/rocm/apt/debian/pool/main/r/rock-dkms/rock-dkms_1.7.137-ubuntu_all.deb
Also according to Phoronix, some Vega compute patches are excluded from 4.17 – I assume they are present in rock-dkms.

**Comment by Ezzestus** [comment] 2018-07-17 03:37
Ya, at this point it sounds like linux 4.19 will get this rolling. Heres hoping.

**Comment by HarlemSquirrel** [comment] 2018-09-15 06:02
I'm trying to get just openCL installed with this [PKGBUILD](https://gist.github.com/HarlemSquirrel/ea923e07f492ed6cc451a60584ada630) I wrote but am having some issues.

**Comment by ruben2000de** [comment] 2018-11-15 14:00
@HarlemSquirrel I have the same problem with Manjaro. opencl-mesa not working at all and opencl-amd(18.30) via AUR results in only invalid shares. rocm via AUR is also outdated.

**Comment by furkan-kucuk** [comment] 2018-11-18 20:12
Can someone add an AUR package for newbie users like me? I would be super grateful if someone provide an updated package like that.

**Comment by HarlemSquirrel** [comment] 2018-11-18 22:01
I tried but couldn't get it working.

**Comment by maxcr** [comment] 2018-11-18 23:44
I've been creating and fixing the upstream AUR PKGBUILDs to work from the latest debian/ubuntu redistributables. There are some patches with need to be applied to the AMDGPU headers from Ubuntu/Debian that's just to get the DKMS working. I was able to build the HSA from scratch using the latest upstream/master repo. Although it requires using GCC7 and 3.12<=bin-utils. The rest of the source code is built in this manner. Its fairly easy to build from source but trying to packages all the binaries in a manner similar to Ubuntu would be very time consuming. If you guys wanna throw me some cash on PayPal to make it worth my while I'll do it but I don't think I can justify taking 2-3 days away from my client to get this working.

**Comment by drewmccal** [comment] 2018-12-03 02:12
I second Arch support!

**Comment by furkan-kucuk** [comment] 2018-12-24 09:51
> rocr-runtime

Can you make a documentation for how to install ROCm stack on arch based system with the same outputs of the installation process for ubuntu? I find using ubuntu is very inconvenient and I would like to switch to arch based distro if possible. The community (at least I) will be very grateful if you provide a document like this.

**Comment by lss4** [comment] 2019-04-10 00:24
Not sure if any AUR maintainers are here, but as of today the packages on AUR (rocm-opencl-runtime) doesn't seem to work properly. After install clinfo sees nothing after installing several of those. I'm using trizen as AUR helper and apparently I'm experiencing other issues mentioned in recent AUR comments as well.

I recall it used to work properly with rocm-opencl-git, but that PKGBUILD is not on AUR anymore.

**Comment by Lukew0rm** [comment] 2019-04-23 13:32
Has anyone succeeded in installing ROCm for Raven Ridge mobile using Arch or Arch-based distros such as Manjaro?
I am currently on kernel 5.0.9 and I have a notebook with Ryzen 2500u.
Which package from the AUR should I try to install? rocm-opencl-runtime? Some others?
Should ROCm work just after installing it or should I apply some tweaks?

**Comment by baerbock** [comment] 2019-07-07 09:51
@Lukew0rm Manjaro is a beginner's distribution, not meant for real tasks.

**Comment by toshi2k2** [comment] 2020-01-03 03:25
@baerbock Pretty big douche aren't you?

**Comment by acxz** [comment] 2020-02-29 01:32
I know this is some time ago, but I just want to put this here in case others come across it. The ArchLinux community including me and some other folks have started picking up development on getting the ROCm stack working here: https://github.com/rocm-arch/rocm-arch. Feel free to submit PRs or issues! It would be best if the Arch community works together on one set of PKGBUILDs instead of splintering away.

**Comment by Rmalavally** [comment] 2020-06-07 21:18
The user contributed ArchLinux installation instructions are available at:

https://community.amd.com/thread/253882

_**Note**: The following installation instructions for ArchLinux is contributed by users. Arch Linux is not currently supported by AMD ROCm and there is no obligation to correct issues that are observed or occur.  Please submit any issues you encounter at the rocm-arch `issue tracker`_._

**Comment by acxz** [comment] 2020-06-07 23:29
@Rmalavally I think with that post this issue can be closed, since all specific ROCm questions on Arch Linux will come over our way at https://github.com/rocm-arch/rocm-arch.

As for specific build issues the rocm-arch community has, we will open up targeted issues at the respective repos issue tracker.

@Rmalavally Thank you so much for creating that post!

**Comment by ROCmSupport** [comment] 2021-01-05 09:47
Closing this issue as per above comments.
Thank you.

**Closed by ROCmSupport** 2021-01-05 09:47 UTC
Labels: Feature Request
