### ISSUE TITLE
Please support Debian

### ISSUE THREAD

**Issue by valeriob01** [RadeonOpenCompute/ROCm#592] opened 2018-10-29 09:00 UTC
I will be happy to use ROCm, under Debian.
Ubuntu is a derivative of Debian, so it should be easy for you to support Debian.

**Comment by jlgreathouse** [comment] 2018-10-29 14:11
Dupe of #304

**Closed by jlgreathouse** 2018-10-29 14:11 UTC

**Comment by chriselrod** [comment] 2018-10-31 06:02
For now, take a look at [this comment](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/1047471-amd-rocm-1-9-available-with-vega-20-support-plus-upstream-kernel-compatibility/page2#post1047548).
I had everything working in the tensorflow-rocm Docker image on Debian a few weeks earlier, following that comment.
