### ISSUE TITLE
ubuntu 16.04 Rocm 1.9 can't workaround

### ISSUE THREAD

**Issue by tom21tom21** [RadeonOpenCompute/ROCm#558] opened 2018-09-26 07:20 UTC
CPU:E5 2670 v2
GPU:RX580
System:Ubuntu 16.04
Kernel:4.15.0-34-generic 

I tried two days and referenced many issue. But the problem is the same.

PS. The OS reinstall.
```
$ /opt/rocm/bin/rocminfo
hsa api call failure at line 900, file: /home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.9/rocminfo/rocminfo.cc. Call returned 4104
```
```
$ /opt/rocm/opencl/bin/x86_64/clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (2671.3)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon RX 580 Series
  Device Topology:                               PCI[ B#2, D#0, F#0 ]
  Max compute units:                             36
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1360Mhz
  Address bits:                                  64
  Max memory allocation:                         4244635648
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            8200589312
  Constant buffer size:                          4244635648
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   0x7ff074545190
  Name:                                          Ellesmere
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 1.2
  Driver version:                                2671.3
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2671.3)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event
```
```
 python /opt/rocm/bin/rocm_smi.py


====================    ROCm System Management Interface    ====================
================================================================================
 GPU  Temp    AvgPwr   SCLK     MCLK     Fan      Perf    SCLK OD    MCLK OD
  0   37c     29.225W  300Mhz   300Mhz   42.75%   auto      0%         0%
================================================================================
====================           End of ROCm SMI Log          ====================
```

```
python /opt/rocm/bin/rocm_smi.py -p


====================    ROCm System Management Interface    ====================
================================================================================
GPU[0]          : Current PowerPlay Level: auto
================================================================================
====================           End of ROCm SMI Log          ====================
```

```
lspci -tv
-+-[0000:ff]-+-08.0  Intel Corporation Xeon E5/Core i7 QPI Link 0
 |           +-08.3  Intel Corporation Xeon E5/Core i7 QPI Link Reut 0
 |           +-08.4  Intel Corporation Xeon E5/Core i7 QPI Link Reut 0
 |           +-09.0  Intel Corporation Xeon E5/Core i7 QPI Link 1
 |           +-09.3  Intel Corporation Xeon E5/Core i7 QPI Link Reut 1
 |           +-09.4  Intel Corporation Xeon E5/Core i7 QPI Link Reut 1
 |           +-0a.0  Intel Corporation Xeon E5/Core i7 Power Control Unit 0
 |           +-0a.1  Intel Corporation Xeon E5/Core i7 Power Control Unit 1
 |           +-0a.2  Intel Corporation Xeon E5/Core i7 Power Control Unit 2
 |           +-0a.3  Intel Corporation Xeon E5/Core i7 Power Control Unit 3
 |           +-0b.0  Intel Corporation Xeon E5/Core i7 Interrupt Control Registers
 |           +-0b.3  Intel Corporation Xeon E5/Core i7 Semaphore and Scratchpad Configuration Registers
 |           +-0c.0  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0c.1  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0c.2  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0c.3  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0c.6  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller System Address Decoder 0
 |           +-0c.7  Intel Corporation Xeon E5/Core i7 System Address Decoder
 |           +-0d.0  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0d.1  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0d.2  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0d.3  Intel Corporation Xeon E5/Core i7 Unicast Register 0
 |           +-0d.6  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller System Address Decoder 1
 |           +-0e.0  Intel Corporation Xeon E5/Core i7 Processor Home Agent
 |           +-0e.1  Intel Corporation Xeon E5/Core i7 Processor Home Agent Performance Monitoring
 |           +-0f.0  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Registers
 |           +-0f.1  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller RAS Registers
 |           +-0f.2  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 0
 |           +-0f.3  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 1
 |           +-0f.4  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 2
 |           +-0f.5  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 3
 |           +-0f.6  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Target Address Decoder 4
 |           +-10.0  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 0
 |           +-10.1  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 1
 |           +-10.2  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 0
 |           +-10.3  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 1
 |           +-10.4  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 2
 |           +-10.5  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller Channel 0-3 Thermal Control 3
 |           +-10.6  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 2
 |           +-10.7  Intel Corporation Xeon E5/Core i7 Integrated Memory Controller ERROR Registers 3
 |           +-11.0  Intel Corporation Xeon E5/Core i7 DDRIO
 |           +-13.0  Intel Corporation Xeon E5/Core i7 R2PCIe
 |           +-13.1  Intel Corporation Xeon E5/Core i7 Ring to PCI Express Performance Monitor
 |           +-13.4  Intel Corporation Xeon E5/Core i7 QuickPath Interconnect Agent Ring Registers
 |           +-13.5  Intel Corporation Xeon E5/Core i7 Ring to QuickPath Interconnect Link 0 Performance Monitor
 |           \-13.6  Intel Corporation Xeon E5/Core i7 Ring to QuickPath Interconnect Link 1 Performance Monitor
 \-[0000:00]-+-00.0  Intel Corporation Xeon E5/Core i7 DMI2
             +-02.0-[01]--
             +-03.0-[02]--+-00.0  Advanced Micro Devices, Inc. [AMD/ATI] Device 67df
             |            \-00.1  Advanced Micro Devices, Inc. [AMD/ATI] Device aaf0
             +-05.0  Intel Corporation Xeon E5/Core i7 Address Map, VTd_Misc, System Management
             +-05.2  Intel Corporation Xeon E5/Core i7 Control Status and Global Errors
             +-05.4  Intel Corporation Xeon E5/Core i7 I/O APIC
             +-11.0-[03]--
             +-16.0  Intel Corporation C600/X79 series chipset MEI Controller #1
             +-1a.0  Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #2
             +-1b.0  Intel Corporation C600/X79 series chipset High Definition Audio Controller
             +-1c.0-[04]--
             +-1c.2-[05]----00.0  Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
             +-1c.3-[06]----00.0  VIA Technologies, Inc. VL805 USB 3.0 Host Controller
             +-1d.0  Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #1
             +-1e.0-[07]--
             +-1f.0  Intel Corporation C600/X79 series chipset LPC Controller
             +-1f.2  Intel Corporation C600/X79 series chipset 6-Port SATA AHCI Controller
             \-1f.3  Intel Corporation C600/X79 series chipset SMBus Host Controller
```

```
lspci -n
00:00.0 0600: 8086:3c00 (rev 07)
00:02.0 0604: 8086:3c04 (rev 07)
00:03.0 0604: 8086:3c08 (rev 07)
00:05.0 0880: 8086:3c28 (rev 07)
00:05.2 0880: 8086:3c2a (rev 07)
00:05.4 0800: 8086:3c2c (rev 07)
00:11.0 0604: 8086:1d3e (rev 06)
00:16.0 0780: 8086:1d3a (rev 05)
00:1a.0 0c03: 8086:1d2d (rev 06)
00:1b.0 0403: 8086:1d20 (rev 06)
00:1c.0 0604: 8086:1d10 (rev b6)
00:1c.2 0604: 8086:1d14 (rev b6)
00:1c.3 0604: 8086:1d16 (rev b6)
00:1d.0 0c03: 8086:1d26 (rev 06)
00:1e.0 0604: 8086:244e (rev a6)
00:1f.0 0601: 8086:1d41 (rev 06)
00:1f.2 0106: 8086:1d02 (rev 06)
00:1f.3 0c05: 8086:1d22 (rev 06)
02:00.0 0300: 1002:67df (rev e7)
02:00.1 0403: 1002:aaf0
05:00.0 0200: 10ec:8168 (rev 07)
06:00.0 0c03: 1106:3483 (rev 01)
ff:08.0 0880: 8086:3c80 (rev 07)
ff:08.3 0880: 8086:3c83 (rev 07)
ff:08.4 0880: 8086:3c84 (rev 07)
ff:09.0 0880: 8086:3c90 (rev 07)
ff:09.3 0880: 8086:3c93 (rev 07)
ff:09.4 0880: 8086:3c94 (rev 07)
ff:0a.0 0880: 8086:3cc0 (rev 07)
ff:0a.1 0880: 8086:3cc1 (rev 07)
ff:0a.2 0880: 8086:3cc2 (rev 07)
ff:0a.3 0880: 8086:3cd0 (rev 07)
ff:0b.0 0880: 8086:3ce0 (rev 07)
ff:0b.3 0880: 8086:3ce3 (rev 07)
ff:0c.0 0880: 8086:3ce8 (rev 07)
ff:0c.1 0880: 8086:3ce8 (rev 07)
ff:0c.2 0880: 8086:3ce8 (rev 07)
ff:0c.3 0880: 8086:3ce8 (rev 07)
ff:0c.6 0880: 8086:3cf4 (rev 07)
ff:0c.7 0880: 8086:3cf6 (rev 07)
ff:0d.0 0880: 8086:3ce8 (rev 07)
ff:0d.1 0880: 8086:3ce8 (rev 07)
ff:0d.2 0880: 8086:3ce8 (rev 07)
ff:0d.3 0880: 8086:3ce8 (rev 07)
ff:0d.6 0880: 8086:3cf5 (rev 07)
ff:0e.0 0880: 8086:3ca0 (rev 07)
ff:0e.1 1101: 8086:3c46 (rev 07)
ff:0f.0 0880: 8086:3ca8 (rev 07)
ff:0f.1 0880: 8086:3c71 (rev 07)
ff:0f.2 0880: 8086:3caa (rev 07)
ff:0f.3 0880: 8086:3cab (rev 07)
ff:0f.4 0880: 8086:3cac (rev 07)
ff:0f.5 0880: 8086:3cad (rev 07)
ff:0f.6 0880: 8086:3cae (rev 07)
ff:10.0 0880: 8086:3cb0 (rev 07)
ff:10.1 0880: 8086:3cb1 (rev 07)
ff:10.2 0880: 8086:3cb2 (rev 07)
ff:10.3 0880: 8086:3cb3 (rev 07)
ff:10.4 0880: 8086:3cb4 (rev 07)
ff:10.5 0880: 8086:3cb5 (rev 07)
ff:10.6 0880: 8086:3cb6 (rev 07)
ff:10.7 0880: 8086:3cb7 (rev 07)
ff:11.0 0880: 8086:3cb8 (rev 07)
ff:13.0 0880: 8086:3ce4 (rev 07)
ff:13.1 1101: 8086:3c43 (rev 07)
ff:13.4 1101: 8086:3ce6 (rev 07)
ff:13.5 1101: 8086:3c44 (rev 07)
ff:13.6 0880: 8086:3c45 (rev 07)
```
```
$lsmod
Module                  Size  Used by
nls_iso8859_1          16384  2
intel_rapl             20480  0
sb_edac                24576  0
x86_pkg_temp_thermal    16384  0
intel_powerclamp       16384  0
coretemp               16384  0
snd_hda_codec_realtek   106496  1
snd_hda_codec_hdmi     49152  1
snd_hda_codec_generic    73728  1 snd_hda_codec_realtek
kvm_intel             212992  0
kvm                   598016  1 kvm_intel
snd_hda_intel          40960  5
snd_hda_codec         126976  4 snd_hda_intel,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec_realtek
irqbypass              16384  1 kvm
snd_hda_core           81920  5 snd_hda_intel,snd_hda_codec,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_hda_codec_realtek
crct10dif_pclmul       16384  0
crc32_pclmul           16384  0
snd_hwdep              20480  1 snd_hda_codec
ghash_clmulni_intel    16384  0
pcbc                   16384  0
snd_pcm                98304  4 snd_hda_intel,snd_hda_codec,snd_hda_core,snd_hda_codec_hdmi
snd_seq_midi           16384  0
snd_seq_midi_event     16384  1 snd_seq_midi
joydev                 24576  0
input_leds             16384  0
snd_rawmidi            32768  1 snd_seq_midi
aesni_intel           188416  0
aes_x86_64             20480  1 aesni_intel
crypto_simd            16384  1 aesni_intel
glue_helper            16384  1 aesni_intel
cryptd                 24576  3 crypto_simd,ghash_clmulni_intel,aesni_intel
snd_seq                65536  2 snd_seq_midi_event,snd_seq_midi
intel_cstate           20480  0
intel_rapl_perf        16384  0
snd_seq_device         16384  3 snd_seq,snd_rawmidi,snd_seq_midi
snd_timer              32768  2 snd_seq,snd_pcm
serio_raw              16384  0
snd                    81920  21 snd_hda_intel,snd_hwdep,snd_seq,snd_hda_codec,snd_timer,snd_rawmidi,snd_hda_codec_hdmi,snd_hda_codec_generic,snd_seq_device,snd_hda_codec_realtek,snd_pcm
mei_me                 40960  0
lpc_ich                24576  0
mei                    90112  1 mei_me
soundcore              16384  1 snd
shpchp                 36864  0
mac_hid                16384  0
parport_pc             36864  1
ppdev                  20480  0
lp                     20480  0
parport                49152  3 lp,parport_pc,ppdev
autofs4                40960  2
uas                    24576  0
usb_storage            69632  2 uas
hid_logitech_hidpp     32768  0
hid_logitech_dj        20480  0
hid_generic            16384  0
usbhid                 49152  0
hid                   118784  6 hid_generic,usbhid,hid_logitech_dj,hid_logitech_hidpp
amdkfd                180224  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               2732032  53
chash                  16384  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   106496  1 amdgpu
drm_kms_helper        172032  1 amdgpu
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
psmouse               147456  0
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
ahci                   36864  3
drm                   401408  9 amdgpu,ttm,drm_kms_helper
libahci                32768  1 ahci
r8169                  86016  0
mii                    16384  1 r8169
```

```
$dkms status
amdgpu, 18.30-641594, 4.15.0-34-generic, x86_64: built
amdgpu, 1.9-211, 4.15.0-34-generic, x86_64: built
```

```
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
```

```
$uname -a
Linux horry-desktop 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$dmesg | grep kfd
[    1.949412] kfd kfd: Initialized module
[    2.705392] amdgpu 0000:02:00.0: kfd not supported on this ASIC
```

```
$dmesg | grep amd
[    0.000000] Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 (Ubuntu 4.15.0-34.37~16.04.1-generic 4.15.18)
[    1.944271] [drm] amdgpu kernel modesetting enabled.
[    1.949564] fb: switching to amdgpudrmfb from EFI VGA
[    1.950089] amdgpu 0000:02:00.0: Invalid PCI ROM header signature: expecting 0xaa55, got 0xffff
[    1.950182] amdgpu 0000:02:00.0: VRAM: 8192M 0x000000F400000000 - 0x000000F5FFFFFFFF (8192M used)
[    1.950185] amdgpu 0000:02:00.0: GTT: 256M 0x0000000000000000 - 0x000000000FFFFFFF
[    1.950268] [drm] amdgpu: 8192M of VRAM memory ready
[    1.950269] [drm] amdgpu: 8192M of GTT memory ready.
[    1.950376] amdgpu 0000:02:00.0: amdgpu: using MSI.
[    1.950391] [drm] amdgpu: irq initialized.
[    1.950408] amdgpu: [powerplay] amdgpu: powerplay sw initialized
[    1.950619] amdgpu 0000:02:00.0: fence driver on ring 0 use gpu addr 0x0000000000400040, cpu addr 0x        (ptrval)
[    1.950656] amdgpu 0000:02:00.0: fence driver on ring 1 use gpu addr 0x00000000004000c0, cpu addr 0x        (ptrval)
[    1.950688] amdgpu 0000:02:00.0: fence driver on ring 2 use gpu addr 0x0000000000400140, cpu addr 0x        (ptrval)
[    1.950725] amdgpu 0000:02:00.0: fence driver on ring 3 use gpu addr 0x00000000004001c0, cpu addr 0x        (ptrval)
[    1.950757] amdgpu 0000:02:00.0: fence driver on ring 4 use gpu addr 0x0000000000400240, cpu addr 0x        (ptrval)
[    1.950789] amdgpu 0000:02:00.0: fence driver on ring 5 use gpu addr 0x00000000004002c0, cpu addr 0x        (ptrval)
[    1.950820] amdgpu 0000:02:00.0: fence driver on ring 6 use gpu addr 0x0000000000400340, cpu addr 0x        (ptrval)
[    1.950852] amdgpu 0000:02:00.0: fence driver on ring 7 use gpu addr 0x00000000004003c0, cpu addr 0x        (ptrval)
[    1.950884] amdgpu 0000:02:00.0: fence driver on ring 8 use gpu addr 0x0000000000400440, cpu addr 0x        (ptrval)
[    1.950902] amdgpu 0000:02:00.0: fence driver on ring 9 use gpu addr 0x00000000004004e0, cpu addr 0x        (ptrval)
[    1.951397] amdgpu 0000:02:00.0: fence driver on ring 10 use gpu addr 0x0000000000400560, cpu addr 0x        (ptrval)
[    1.951434] amdgpu 0000:02:00.0: fence driver on ring 11 use gpu addr 0x00000000004005e0, cpu addr 0x        (ptrval)
[    1.951761] amdgpu 0000:02:00.0: fence driver on ring 12 use gpu addr 0x000000f4001e6420, cpu addr 0x        (ptrval)
[    1.951790] amdgpu 0000:02:00.0: fence driver on ring 13 use gpu addr 0x00000000004006e0, cpu addr 0x        (ptrval)
[    1.951817] amdgpu 0000:02:00.0: fence driver on ring 14 use gpu addr 0x0000000000400760, cpu addr 0x        (ptrval)
[    1.951945] amdgpu 0000:02:00.0: fence driver on ring 15 use gpu addr 0x00000000004007e0, cpu addr 0x        (ptrval)
[    1.951975] amdgpu 0000:02:00.0: fence driver on ring 16 use gpu addr 0x0000000000400860, cpu addr 0x        (ptrval)
[    2.687456] fbcon: amdgpudrmfb (fb0) is primary device
[    2.687525] amdgpu 0000:02:00.0: fb0: amdgpudrmfb frame buffer device
[    2.705392] amdgpu 0000:02:00.0: kfd not supported on this ASIC
[    2.705402] [drm] Initialized amdgpu 3.23.0 20150101 for 0000:02:00.0 on minor 0
```
```
$ groups
horry adm cdrom sudo dip plugdev lpadmin sambashare
```

**Comment by jlgreathouse** [comment] 2018-09-26 14:36
I see a few problems with the curren toutput you're showing.

1. Based on your DKMS output, you have amdgpu-pro installed. I would recommend uninstalling this with `amdgpu-pro-uninstall`.
2. Based on your DKMS output, the ROCm driver is not fully installed for your kernel. It is built, but not installed. You can fix this by running `sudo dkms install amdgpu/1.9-211`.
3. Your user is not in the 'video' group. You can fix this `sudo usermod -a -G video $LOGNAME`
4. I'm not 100% sure if your CPU [is on our support list for your GPU](https://rocm.github.io/hardware.html). It appears that the Xeon E5-2600 V2 series _does_ [support PCIe atomics](https://software.intel.com/en-us/articles/intel-xeon-processor-e5-2600-v2-product-family-technical-overview). However, I haven't tested this processor specifically.

**Comment by tom21tom21** [comment] 2018-09-26 14:43
@jlgreathouse  Thank you to your answer.
I will try tomorrow. 
BTW,  I will tell the result asap.

**Comment by tom21tom21** [comment] 2018-09-26 15:51
> @jlgreathouse Thank you to your answer.
> I will try tomorrow.
> BTW, I will tell the result asap.

Sorry The problem can't solve, even I used above method.

**Comment by jlgreathouse** [comment] 2018-09-26 17:44
Could you rerun the following test after a reboot?

- `uname -r`
- `dkms status`
- `modinfo amdgpu | grep filename`
- `modinfo amdkfd | grep filename`
- `dmesg | grep kfd`
- `dmesg | grep amd`

And could you define what you mean by "the problem" in your latest message? What have you tested to verify that this problem still exists? Thanks.

**Comment by jlgreathouse** [comment] 2018-09-27 02:29
Could you reboot your system and please show me the outputs requested in my previous response? Thank you.

**Comment by tom21tom21** [comment] 2018-09-27 02:46
> Could you reboot your system and please show me the outputs requested in my previous response? Thank you.

I already rebooted and add up some the response.

**Comment by jlgreathouse** [comment] 2018-09-27 02:53
Hi @tom21tom21 

The following identifies your problem:
```$ dmesg | grep kfd
[    1.625730] kfd kfd: Initialized module
[    1.626379] kfd kfd: skipped device 1002:67df, PCI rejects atomics
```

Your combination of CPU and GPU [are not supported in ROCm](https://rocm.github.io/hardware.html). Your GPU device, a gfx8 "Polaris 10" Radeon RX 580, requires a CPU that supports PCIe atomics. As discussed on our hardware page, if you want to use a Xeon CPU, this will require a Xeon "v3" or newer (Haswell). Your Xeon E5 2670 v2 apparently does not support PCIe atomics.

Perhaps there is an option in your BIOS to enable this. But as your system is currently configured, our drivers are unable to use PCIe atomics in the way they need. As such, your GPU will not work under ROCm in this system configuration.

**Comment by tom21tom21** [comment] 2018-09-27 02:55
Thank you I will change the other CPU to test.

**Comment by rumatadest** [comment] 2018-09-27 11:05
Under Linux, most AMD cards are currently used for mining. The standard configuration of a mining rig is a computer with a low end CPU like Celeron. With 4-10 GPUs are connected through $3 Chinese risers PCI-E 1x from aliexpress
In this configuration, there can be no support for "PCIe atomics"

In the end, I have to use three versions of the drivers and OS
- kernel 4,15 and amdgpu-pro 17,50 working fine RX 5хх series without any "supports PCIe atomics." but it ugly Power Control and no Vega support
- kernel 4,15 and amdgpu-pro 18,30 - support Vega, but hashrate is lower than windows about 40%
- kernel 4,15 and ROCm 1.9.211 - no PowerControl for Vega and no support RX 5хх/Vega without PCIe atomics
- kernel 4.18 - good PowerControl but rocm-dkms is compiled with an error
- Windows does not have problems with the drivers, but it is very difficult to administer. It is freeze twice a day

**Comment by gstoner** [comment] 2018-09-27 13:42
@rumatadest 
            You only have two drivers in Linux not three for compute.  AMDGPUpro and ROCm

   Again ROCm was designed for different use case then you trying to do, Radio Astronomy, HPC and Deep Learning were it primary market focus when it was conceived,   Coin Minning on GPU was not a real market then.   We had some very advanced hardware that never shipped it was designed to address. 

      - AMDGPUpro will move forward as the driver that runs everywhere and run with the lowest common denominator system and support broadest number CPU and GPU,  it will get Most of the language runtime which runs on ROCm via PAL base user mode runtime and Kernel Mode packet submission.  Note as of 18.20 for Vega10  it uses the same OpenCL Compilers runtime via PAL layer as Windows. It has always used the same  OpenCL Compiler and Language Runtime as windows for GFX8  and Older GPU's     If you having a performance issue  Between windows and 18.30 AMDGPUpro it not OpenCL issue it in the base Linux driver. 

     - ROCm Enterprise driver is targeted at the. NVIDIA Tesla market, supporting  Radeon Instinct product family of hardware,  we support other GPU asics as well for the community to get access to the advanced Software feature it offers.  

On PCIe Atomics,  we have a mode for Vega10 that shuts of PCIe atomics,  we looking make sure there is fall back path for those who do not really care about I/O performance or Queue Submission overheads,  which is your use case.   To do this we have to do Firmware changes, this harder for older hardware which the firmware engineering team are more hesitant to touch.  On ROCm for Future hardware release, we have a fallback path. 

4.18 just came out, Aug 30th   I understand it has the feature you want, right now with ROCm 1.9 you can use it with new changes in the Thunk, but understand it takes time to integrate with the bigger stack flow it out in a formal driver release

**Comment by jlgreathouse** [comment] 2018-09-27 16:33
Hi @rumatadest 

To give a bit more info -- ROCm 1.9.0 supports Linux 4.15 (in particular, Ubuntu 16.04 LTS and 18.04 LTS; the most recent versions of these distributions base their HWE kernel on 4.15). We do support Vega 10 GPUs in ROCm 1.8 and 1.9 on systems without PCIe atomics. In ROCm 1.8 we required you to manually set the environment variable HSA_ENABLE_SDMA=0 to avoid the requirement for PCIe atomics; this is no longer the case in ROCm 1.9.

You are right, however, that GPUs in the gfx8 line, includ Radeon RX 5xx GPUs ("Polaris 10", "Polaris 11") do still require PCIe atomics. You can read more information about these requirements in #451.

If you are running kernel 4.18, you do not need to install the full `rocm-dkms` package to get ROCm software working. As of 4.16 (pre-Vega) and 4.17 (including Vega 10 support), a working version of the ROCK drivers are available in the upstream kernel. As such, you can, if you so choose, skip installing rock-dkms, which is one of the dependencies of rocm-dkms. See [this post](https://github.com/RadeonOpenCompute/ROCm/issues/513#issuecomment-421643966), where I link to directions on Phoronix that show a user getting the ROCm user-level software working on the base 4.18 kernel.

We are aware that the ROCm 1.9.0 rock-dkms package won't build on newer kernels. However, AMD's custom ROCm drivers available as part of ROCm 1.9.0 are only supported on RHEL/CentOS 7.4 and 7.5, and on Ubuntu 16.04 LTS and Ubuntu 18.04 LTS. As such, we do not guarantee that they will work on newer kernels that are not officially supported on these distros. For newer kernels, however, you should be able to use the upstream drivers with our user-land software.

**Comment by jlgreathouse** [comment] 2018-09-27 16:34
Hi @tom21tom21

Since the underlying problem reported in this issue is an unsupported CPU+GPU combination, I'm going to close this ticket. If you install a newer CPU and still run into problems, please feel free to open another ticket. Thanks!

**Closed by jlgreathouse** 2018-09-27 16:34 UTC

**Comment by rumatadest** [comment] 2018-09-27 16:57
Thanks for your reply
Waiting for the ebuilds ))

Wishes.
Is it possible to create a test repository with "nightly builds"? Not every person can compile the latest version of the ROCM from the thunk. This can speed up the process of testing new features.

**Comment by jlgreathouse** [comment] 2018-09-27 17:19
Hi @rumatadest 

That's a good request. I don't know if would be able to do "nightly" builds (our internal nightly builds may contain code that we do not wish to release to the public, such as information about new hardware that we have not released). That said, we can try to explore the possibility of unofficial/testing channels. I can't make any promises about this, but thank you for the request.
