### ISSUE TITLE
ROCM 3.9-17 fan not work 

### ISSUE THREAD

**Issue by memsenpai** [RadeonOpenCompute/ROCm#1300] opened 2020-11-23 01:45 UTC
rock-dkms:
  Installed: 1:3.9-17
  Candidate: 1:3.9-17
  Version table:
 *** 1:3.9-17 500
        500 https://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
        100 /var/lib/dpkg/status
Device: gigabyte 5600xt
OS: Ubuntu 20.04.1 LTS

rocm-smi
```
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan   Perf  PwrCap  VRAM%  GPU%  
0    49.0c  31.0W   800Mhz  875Mhz  100.0%  auto  180.0W   12%   16%   
================================================================================
============================= End of ROCm SMI Log ==============================
```

but when I look at the vga and can't see the fan spinning

in 3.5, it work normal. in this version, i can set fan speed but fan not spin. anyuone know reason or have any idea for fix it ? thanks

**Comment by ROCmSupport** [comment] 2020-11-23 06:17
Thanks @memsenpai for reaching out.
We will check and get back asap.

**Comment by memsenpai** [comment] 2020-11-23 06:43
@ROCmSupport 
one more, maybe helpful.
i checked on windoww  with app of amd, it show max fan speed ~4000 rpm
but when i set 100% with rocm-smi, i see in info show fan speed is ~14000 rpm(Even though the fans are still not really active)

**Comment by ROCmSupport** [comment] 2020-11-23 12:23
Thanks for the additional information @memsenpai 
Looks like its hardware issue for me, as software functions are working properly.

**Comment by memsenpai** [comment] 2020-11-24 01:36
@ROCmSupport but it still work on rocm 3.5 
have any way help me rollback to version 3.5 ?

**Comment by ROCmSupport** [comment] 2020-11-24 07:21
Hi @memsenpai 
Are you sure that fan runs on ROCm 3.5, please confirm asap.
You can install ROCm 3.5/3.5.1 from **http://repo.radeon.com/rocm/apt/3.5.1** space

**Comment by memsenpai** [comment] 2020-11-26 01:49
@ROCmSupport  i rollback to 3.8 and it working now
even rocm-smi report fan speed not correct (alway 0%)
hardward-info same
but i set by https://github.com/DominiLux/amdgpu-pro-fans and i check by my eye in vga and saw fan spinning.
totally
with 3.8: rocm-smi and hardware-info report incorrect fan speed(as command rocm-smi --setfan 10), alway return 0 but fan spin and work normal.
with 3.9: rocm-smi and hardware-info report correct fan speed(as command rocm-smi --setfan 10) but fan not spin.

**Comment by ROCmSupport** [comment] 2020-11-26 06:54
Thanks @memsenpai.
Can you please help us with below information.
/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo

**Comment by memsenpai** [comment] 2020-11-26 08:40
@ROCmSupport  here, for you
/opt/rocm/bin/rocminfo

```

ROCk module is loaded
Able to open /dev/kfd read-write
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4300                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16331632(0xf93370) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16331632(0xf93370) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx1010                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 29471(0x731f)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1780                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        80(0x50)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    6275072(0x5fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1010         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done *** 
```

/opt/rocm/opencl/bin/clinfo


```
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (3186.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
  Device Topology:				 PCI[ B#3, D#0, F#0 ]
  Max compute units:				 18
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1780Mhz
  Address bits:					 64
  Max memory allocation:			 5461822668
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 29471
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 6425673728
  Constant buffer size:				 5461822668
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 1166855372
  Max global variable size:			 5461822668
  Max global variable preferred total size:	 6425673728
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 8388608
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 32
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7faae9374cd0
  Name:						 gfx1010
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 3186.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 


```

**Comment by ROCmSupport** [comment] 2020-11-26 08:54
Hi @memsenpai 
We are not officially supporting Navi10 series of cards with ROCm. You can check the docs for more clarity.
(Our test teams are not validating too and so I do not have an ready answer)
Anyway I will try to gather more information to answer this question, if possible.

**Comment by ptitjes** [comment] 2020-11-27 00:40
> We are not officially supporting Navi10 series of cards with ROCm. You can check the docs for more clarity.

Release 20.45 of amdgpu-pro now uses ROCm as an OpenCL driver. So are we supposed to understand that AMD Navi10 graphics card aren't supported by any AMD driver ?

**Comment by ROCmSupport** [comment] 2020-11-27 05:14
Hi @ptitjes 
Navi10 support is there with amdgpu-pro driver. But ROCm official support is not there.

**Comment by ROCmSupport** [comment] 2020-11-27 13:10
Hi @memsenpai 
We are not observing this issue locally on ROCm 3.9.
Fan values are perfectly showing and fans are spinning too with SMI for both Vega10 and Radeon7.

**Comment by ptitjes** [comment] 2020-11-28 02:06
@ROCmSupport, well, with ROCm now being part of AMDGPU-PRO, you obviously and implicitly have to support Navi10 and Big Navi. You should update your front-page!

**Comment by memsenpai** [comment] 2020-11-28 07:54
@ROCmSupport i try 3.9 and 3.9.1, both showing fake speed and fan not spin. I also have no experience for error checking. I will wait for the next version to try again

**Comment by ROCmSupport** [comment] 2020-11-30 05:02
Hi @memsenpai 
Let me try checking on a different hardware and will update you soon.
Thank you.

**Comment by ROCmSupport** [comment] 2020-12-11 05:11
Hi @memsenpai 
I recommend you to try with 3.10 which has updated rock-dkms rock-dkms-firmware packages which have the fix for 5.4.0-56 kernel.
Can you please try with the latest 3.10 repo as of today and update your findings.
Thank you.

**Comment by memsenpai** [comment] 2020-12-16 09:58
@ROCmSupport  it ok if i use 5.4.0-54 ?

**Comment by ROCmSupport** [comment] 2020-12-16 10:04
Hi @memsenpai 
You can test it with 5.4.0-54 kernel. It works.

**Comment by memsenpai** [comment] 2020-12-16 10:13
@ROCmSupport 
i tested, it's still the same error as before.

**Comment by ROCmSupport** [comment] 2020-12-16 10:30
Hi @memsenpai 
Issue should not land now as the ROCm 3.10 repo has been updated with fixed kernel packages.
Recommend to do clean uninstall and fresh install of 3.10 again, should work

**Comment by memsenpai** [comment] 2020-12-16 10:39
@ROCmSupport  can you tell me how to clean uninstall ?
i just try follow this guide https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html try to remove 3.10 and reinstall 3.8 (work with me before update to 3.10) but everything still broken.
package version back to 3.8 but stilll has error and fan not work.

**Comment by ROCmSupport** [comment] 2020-12-16 12:35
Recommend to do a fresh 3.10 install(repo has been updated with fixed packages for kernel and so recommending).

**Uninstall ROCm:**
1. sudo apt autoremove rocm-dkms
2. Check if any packages are left, by sudo dpkg -l | grep <pkg>
<pkg> means hsa, hip, llvm, comgr, rock, rocm
If you find any packages from above, remove all packages as sudo apt purge <pkg name>
3. Once all removed, reboot
4. Map the repo again and install the latest ROCm using sudo apt install rocm-dkms
5. Thank you.

**Comment by memsenpai** [comment] 2020-12-17 01:13
@ROCmSupport 
thank you for help me many.
after i try fresh install 3.10, kernel 5.4.0-54, it's still the same error as before.

**Comment by ROCmSupport** [comment] 2020-12-17 03:27
Hi @memsenpai 
I am not able to reproduce the issue with 5.4.0-54.
Can you please share the error logs.

**Comment by memsenpai** [comment] 2020-12-17 06:58
@ROCmSupport 
How can I get the error log for you?
For me, it doesn't give any error, simply the fan is not working.
i try
rocm-smi --setfan 30%
rocm-smi return fan speed working with 100% and 4000rpm

i try
rocm-smi --setfan 100%
rocm-smi return fan speed working with 100% and 12000 rpm
(sensor working wrong? fan's max speed parameter wrong?)

In fact, I checked it with my eyes, the fans weren't spin.

**Comment by ROCmSupport** [comment] 2020-12-17 07:58
Thanks.
I have passed this info to dev and let me try to get more information for you.
Thank you.

**Comment by memsenpai** [comment] 2020-12-17 10:45
@ROCmSupport  i updated log boot, maybe it help. thanks for support me

**Comment by ROCmSupport** [comment] 2021-01-05 07:33
Hi @memsenpai 
Is it still reproducible with ROCm 4.0?
Please test with 4.0 and update asap.

CC: @kentrussell

**Comment by kentrussell** [comment] 2021-01-05 12:29
If the fan isn't spinning, but the system thinks that the fan is still moving (as indicated above), then there are 2 likely culprits. Either the sensor is broken (statistically less likely), or there is a hardware issue. 

1-Can you manually spin the fan with your finger? If not, then there could be something jamming the fan and is causing it to not spin. 
2-If it can spin freely, check if there are any loose connectors on the card (some older models had a 2pin connector for fan power). 
If there are no obvious loose wires and the fan spins manually, then I would consider an RMA for the card as it would either be a bad sensor (nothing anyone can do about that) or a bad fan (could potentially be repaired, but if it's under warranty, just replace the card)

**Comment by ddobreff** [comment] 2021-01-07 22:22
Hi @kentrussell , if you are referring to this patch: https://patchwork.freedesktop.org/patch/397122/?series=83066&rev=2
It fixes fan speed settings in manual mode but the problem with not able to set 100%(ends up at around 81%) persists. The problem affects only swsmu devices, Vega10, Vega20 and Polaris are not affected.
The new approach to setup fans for swsmu for me doesn't work at all, and I'm using reference 5700 which is supposed to be least affected by AIB vendor modifications.
-> https://cgit.freedesktop.org/~agd5f/linux/commit/?h=amd-staging-drm-next&id=337b57aecb3e11294b0e547aac871a5481fd42ed

**Comment by memsenpai** [comment] 2021-01-08 10:27
@ROCmSupport @kentrussell 
i tested with 4.0 and everything is the same as before.

**Comment by kentrussell** [comment] 2021-01-08 13:01
@ddobreff There are a few patches, but there is also https://www.mail-archive.com/amd-gfx@lists.freedesktop.org/msg55933.html . Unfortunately 4.0 doesn't have these fixes, they will be in 4.1 when we move to the newer kernel base.

**Comment by ddobreff** [comment] 2021-01-08 15:55
@kentrussell tried that too, same result, fan cannot exceed 81% on Navi10 reference design. Also have Navi21 if you wish I can perform the test and report, but for now old way seems to work ok.

**Comment by kentrussell** [comment] 2021-01-08 16:04
Thanks @ddobreff  . Once we get 4.1 release out, we can revisit this issue as well as @memsenpai 's issue. We won't be backporting fixes to the 5.6-based branch but if we can see the issue on 4.1, we can start testing fixes on the newer code base, and can also get the amdgpu (kernel and PM) guys looking into it as well (they won't look into deprecated kernel bases).
As a temporary investigation, you could try the 20.45 Pro driver or the open-sourced amdgpu driver and see if the issue continues to persist there too. If it's on the upstream amd-staging-drm-next kernel as well, then it's easier to reproduce and easier to get isolated.  But it's a lot of time and effort, and makes ROCm work a lot harder. But if you're bored in lockdown and have nothing else to do, then those are a couple things to try that can alleviate your boredom until we drop 4.1

**Comment by ROCmSupport** [comment] 2021-02-10 10:18
Hi @memsenpai and all,
I have verified with the latest internal build which will go for ROCm 4.1, hardware fan is running in my case.
Request you to verify with the latest ROCm 4.1.
Thank you.

**Comment by ROCmSupport** [comment] 2021-03-30 10:42
No issue with 4.1, am closing this.
Thank you.

**Closed by ROCmSupport** 2021-03-30 10:42 UTC
