### ISSUE TITLE
On vega64, rocm 1.9.0: luxmark 3.1 and blender 2.79 not works

### ISSUE THREAD

**Issue by sp82** [RadeonOpenCompute/ROCm#555] opened 2018-09-23 13:39 UTC
Hi,
in particular the 2 programs wait long time in "...Compiling kernels ..." than nothing happend.
Best Regards,
Salvatore.

**Comment by kentrussell** [comment] 2018-09-25 11:14
Can you attach a dmesg? Did these work in 1.8 or are you only trying it now in 1.9?

**Comment by jlgreathouse** [comment] 2018-09-25 15:21
I believe he means the OpenCL kernels, rather than the Linux kernel modules.  I suspect this is a dupe of the Blender problem in #503

**Comment by sp82** [comment] 2018-09-26 15:06
I tested with 1.8 on Ubuntu16.04 and 1.9 on Ubuntu18.04. 
Broken in both cases the compilation of OpenCL kernels.

**Comment by illwieckz** [comment] 2018-10-16 17:52
I face the same issue with Luxmark 3.1 (Ubuntu 18.04 and Radeon R9 390X here). The _LuxBall HDR_ benchmark runs and completes (see [results](http://www.luxmark.info/node/5725)) and performs better than my [previous attempt](http://www.luxmark.info/node/3629) with AMDGPU-PRO but the _Microphone_ benchmark never stops to compile OpenCL kernel, o r I have not waited enough.

While compiling OpenCL kernel the `Graphics pipe` bar in [`radeontop`](https://github.com/clbr/radeontop) shows a 100% usage while other statistic bars are idling. CPU usage is idling too. It behaves like an infinite loop.

**Comment by boberfly** [comment] 2018-11-07 09:51
I just tried with the latest bleeding edge branch of Mesa's OpenCL 1.1:
http://luxmark.info/node/5806
Speed demon :)
ROCm/AMD-APP 2679.0 isn't as good unfortunately:
http://luxmark.info/node/5807

**Comment by ubombi** [comment] 2018-11-23 22:05
Same on manjaro _(Kernel: 4.19.1-1)_ ; ROCm: 1.9
Packages from AMD's ubuntu repository converted via `deptap`.

It can render just a basic blender cube and freeze on any real scene.

**Comment by sp82** [comment] 2018-12-01 07:44
still not working.

**Comment by ROCmSupport** [comment] 2020-12-16 12:22
This is 2 years old issue and the environment is very old.
Recommend to try with the latest ROCm release and file a ticket if any.

**Closed by ROCmSupport** 2020-12-16 12:22 UTC
