### ISSUE TITLE
ROCm 1.9 vs Folding@Home

### ISSUE THREAD

**Issue by e-c-d** [RadeonOpenCompute/ROCm#575] opened 2018-10-05 11:33 UTC
# Problem description

I'm trying to run Folding@Home, and am getting "BAD_WORK_UNIT" errors.

I've [attached logs](https://github.com/RadeonOpenCompute/ROCm/files/2450086/runs.zip) including strace. The simulation program immediately fails with "ERROR:Discrepancy: Forces are blowing up! 1 0". This happens over and over for different tasks from the F@H servers.

The card is a Vega 56.

# Steps to reproduce

- Install ROCm 1.9 on a Debian/Ubuntu system
- Set up `/etc/profile.d/rocm.sh` with `HSA_ENABLE_SDMA=0`.
- Install FAHClient from https://foldingathome.org/start-folding/
- Create a new user account, call it "fold". Add to `video` group.
- Log in as that account, make sure env variables are ok.
- Create `config.xml` (see below).
- Run `FAHClient --config config.xml`.

# Logs

```
$ cat /etc/profile.d/rocm.sh
export LD_LIBRARY_PATH=/opt/rocm/opencl/lib/x86_64:/opt/rocm/hsa/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/opt/rocm/bin:/opt/rocm/profiler/bin:/opt/rocm/opencl/bin/x86_64

export HSA_ENABLE_SDMA=0
```

```
$ cat config.xml
<config>
  <!-- Client Control -->
  <fold-anon v='true'/>

  <!-- HTTP Server -->
  <allow v='127.0.0.1 10.3.0.1'/>

  <!-- Slot Control -->
  <power v='full'/>

  <!-- User Information -->
<!--  <user v=''/>
  <passkey v='/> -->

  <!-- Web Server -->
  <web-allow v='127.0.0.1 10.3.0.1'/>

  <!-- Folding Slots -->

<!--  <slot id='0' type='CPU'/> -->

  <slot id='1' type='GPU'>
<!-- <client-type v='beta'/> -->
<!--    <opencl-index v='0'/> -->
  </slot>
</config>
```

```
$ /opt/rocm/bin/rocminfo
=====================
HSA System Attributes
=====================
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE
System Endianness:       LITTLE

==========
HSA Agents
==========
*******
Agent 1
*******
  Name:                    Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Vendor Name:             CPU
  Feature:                 None specified
  Profile:                 FULL_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        0
  Queue Min Size:          0
  Queue Max Size:          0
  Queue Type:              MULTI
  Node:                    0
  Device Type:             CPU
  Cache Info:
    L1:                      32768KB
  Chip ID:                 0
  Cacheline Size:          64
  Max Clock Frequency (MHz):3600
  BDFID:                   0
  Compute Unit:            4
  Features:                None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    10168564KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Acessible by all:        TRUE
    Pool 2
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    10168564KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Acessible by all:        TRUE
  ISA Info:
    N/A
*******
Agent 2
*******
  Name:                    gfx900
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
  Profile:                 BASE_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        128
  Queue Min Size:          4096
  Queue Max Size:          131072
  Queue Type:              MULTI
  Node:                    1
  Device Type:             GPU
  Cache Info:
    L1:                      16KB
  Chip ID:                 26751
  Cacheline Size:          64
  Max Clock Frequency (MHz):1622
  BDFID:                   768
  Compute Unit:            56
  Features:                KERNEL_DISPATCH
  Fast F16 Operation:      FALSE
  Wavefront Size:          64
  Workgroup Max Size:      1024
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888
    Dim[1]:                  50332672
    Dim[2]:                  0
  Grid Max Size:           4294967295
  Waves Per CU:            40
  Max Work-item Per CU:    2560
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295
    Dim[1]:                  4294967295
    Dim[2]:                  4294967295
  Max number Of fbarriers Per Workgroup:32
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    8372224KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Alignment:         4KB
      Acessible by all:        FALSE
    Pool 2
      Segment:                 GROUP
      Size:                    64KB
      Allocatable:             FALSE
      Alloc Granule:           0KB
      Alloc Alignment:         0KB
      Acessible by all:        FALSE
  ISA Info:
    ISA 1
      Name:                    amdgcn-amd-amdhsa--gfx900
      Machine Models:          HSA_MACHINE_MODEL_LARGE
      Profiles:                HSA_PROFILE_BASE
      Default Rounding Mode:   NEAR
      Default Rounding Mode:   NEAR
      Fast f16:                TRUE
      Workgroup Max Dimension:
        Dim[0]:                  67109888
        Dim[1]:                  1024
        Dim[2]:                  16777217
      Workgroup Max Size:      1024
      Grid Max Dimension:
        x                        4294967295
        y                        4294967295
        z                        4294967295
      Grid Max Size:           4294967295
      FBarrier Max Size:       32
*** Done ***
```

```
# dmesg | grep kfd
[    3.572882] kfd kfd: Initialized module
[    4.129673] kfd kfd: Allocated 3969056 bytes on gart
[    4.129817] kfd kfd: added device 1002:687f
```

```
# inxi -sF
System:    Host: nsa Kernel: 4.19.0-rc4-amd64 x86_64 bits: 64 Console: tty 4
           Distro: Debian GNU/Linux buster/sid
Machine:   Type: Desktop System: ASUSTeK product: CM6340 v: N/A serial: CENSORED
           Mobo: ASUSTeK model: CM6340 v: Rev X.0x serial: CENSORED UEFI: American Megatrends v: 0604
           date: 07/11/2013
CPU:       Topology: Quad Core model: Intel Core i5-3470 bits: 64 type: MCP L2 cache: 6144 KiB
           Speed: 1600 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1600 2: 1600 3: 1600 4: 1601
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] driver: amdgpu v: kernel
           Display: server: X.org 1.20.1 driver: amdgpu,ati unloaded: fbdev,modesetting,vesa tty: 136x39
           Message: Advanced graphics data unavailable in console for root.
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio driver: snd_hda_intel
           Device-2: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel
           Sound Server: ALSA v: k4.19.0-rc4-amd64
Network:   Device-1: Ralink RT3090 Wireless 802.11n 1T/1R PCIe driver: rt2800pci
           IF: wlp4s0 state: down mac: CENSORED
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
           IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: CENSORED
           IF-ID-1: ecdmesh state: unknown speed: 10 Mbps duplex: full mac: CENSORED
           IF-ID-2: lxcbr0 state: up speed: N/A duplex: N/A mac: CENSORED
           IF-ID-3: vethLKIYJ7 state: up speed: 10000 Mbps duplex: full mac: CENSORED
Drives:    Local Storage: total: 1.93 TiB used: 190.86 GiB (9.7%)
           ID-1: /dev/sda vendor: Western Digital model: WD20EARS-00MVWB0 size: 1.82 TiB
           ID-2: /dev/sdb vendor: Kingston model: SUV400S37120G size: 111.79 GiB
Partition: ID-1: / size: 100.00 GiB used: 80.25 GiB (80.2%) fs: btrfs dev: /dev/dm-1
           ID-2: /home size: 100.00 GiB used: 80.25 GiB (80.2%) fs: btrfs dev: /dev/dm-1
           ID-3: swap-1 size: 2.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-2
Sensors:   System Temperatures: cpu: 30.0 C mobo: 36.0 C gpu: amdgpu temp: 41 C
           Fan Speeds (RPM): cpu: 0 fan-1: 1062 fan-2: 1510 fan-3: 0 gpu: amdgpu fan: 660
Info:      Processes: 235 Uptime: 12h 56m Memory: 9.70 GiB used: 482.5 MiB (4.9%) Init: systemd runlevel: 5
           Shell: zsh inxi: 3.0.24
```

**Comment by b-sumner** [comment] 2018-10-05 15:20
Last I checked, we were unfortunately failing a few of the OpenMM tests.  I'm running the tests now with the tip OpenMM sources and the tip compilers to see if the situation has changed.

**Comment by b-sumner** [comment] 2018-10-08 22:13
Running the OpenMM OpenCL tests compile from tip sources are passing for me, and apparently others, on ROCm 1.9 on various gfx900 based cards.  I understand the latest release is using a somewhat older version of OpenMM.  Do you get better results using the latest beta, which I understand is using a more recent version of OpenMM?

**Comment by DeeGeeFi** [comment] 2019-06-25 11:17
I just tried to use my Vega 64 with the ROCm opencl drivers and got the same problem. I installed using these instructions https://rocm.github.io/install.html on (K)ubuntu 19.04 and they seemed to work fine otherwise, but F@H still is having the same problem. Also the closed source driver stack hasn't been updated since Ubuntu 18.04... If the ROCm drivers could be made to work even with the old OpenMM binaries F@H uses, it would save lot of headache.

**Comment by Burstaholic** [comment] 2020-03-13 15:49
Their latest GPU core is based on OpenMM 7.4.1, which appears to be the latest, but I still cannot fold with my RX 580. My error message is much more generic (I forget exactly but can reproduce if helpful) but I still end up with `BAD_WORK_UNIT` with `rocm_dev 3.1.35` on Kubuntu 18.04.4 with the HWE `5.3.0-40` kernel.

**Comment by soulhunter** [comment] 2020-03-16 16:33
Hello,

Similar here with Vega10 card.  I get this in the logs:

```
15:36:56:WU01:FS01:0x22:Digital signatures verified
15:36:56:WU01:FS01:0x22:Folding@home GPU Core22 Folding@home Core
15:36:56:WU01:FS01:0x22:Version 0.0.2
15:37:03:WU01:FS01:0x22:Caught signal SIGABRT(6) on PID 55606
15:37:03:WU01:FS01:0x22:WARNING:Unexpected exit from science code
15:37:03:WU01:FS01:0x22:Saving result file ../logfile_01.txt
15:37:03:WU01:FS01:0x22:Saving result file science.log
15:37:03:WU01:FS01:0x22:Folding@home Core Shutdown: BAD_WORK_UNIT
```

I am on Ubuntu 18.04, 5.3.0-40 kernel as well.  Installed ROCM using this sources.list line:

`deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main`

This is "folding" just fine using the CPU, but I have three GPUs that I should be able to use on this.

This is the system info as given by FAHClient:

```
16:29:43:******************************* System ********************************
16:29:43:            CPU: AMD Ryzen Threadripper 1920X 12-Core Processor
16:29:43:         CPU ID: AuthenticAMD Family 23 Model 1 Stepping 1
16:29:43:           CPUs: 24
16:29:43:         Memory: 62.83GiB
16:29:43:    Free Memory: 53.46GiB
16:29:43:        Threads: POSIX_THREADS
16:29:43:     OS Version: 5.3
16:29:43:    Has Battery: false
16:29:43:     On Battery: false
16:29:43:     UTC Offset: NN
16:29:43:            PID: NNNNNN
16:29:43:            CWD: /path/to/fah/work/dir
16:29:43:             OS: Linux 5.3.0-40-generic x86_64
16:29:43:        OS Arch: AMD64
16:29:43:           GPUs: 3
16:29:43:          GPU 0: Bus:8 Slot:0 Func:0 AMD:5 Ellesmere XT [Radeon RX
16:29:43:                 470/480/570/580]
16:29:43:          GPU 1: Bus:65 Slot:0 Func:0 AMD:5 Ellesmere XT [Radeon RX
16:29:43:                 470/480/570/580]
16:29:43:          GPU 2: Bus:68 Slot:0 Func:0 AMD:5 Vega 10 XTX [Radeon Vega Frontier
16:29:43:                 Edition]
16:29:43:           CUDA: Not detected: Failed to open dynamic library 'libcuda.so':
16:29:43:                 libcuda.so: cannot open shared object file: No such file or
16:29:43:                 directory
16:29:43:OpenCL Device 0: Platform:0 Device:0 Bus:8 Slot:0 Compute:1.2 Driver:3084.0
16:29:43:OpenCL Device 1: Platform:0 Device:1 Bus:65 Slot:0 Compute:1.2 Driver:3084.0
16:29:43:OpenCL Device 2: Platform:0 Device:2 Bus:68 Slot:0 Compute:2.0 Driver:3084.0
16:29:43:***********************************************************************
```

Ildefonso

**Comment by akostadinov** [comment] 2020-03-18 18:28
Hitting the same on 3.1 on RHEL 7.7

**Comment by kochd** [comment] 2020-03-19 05:36
Same for me

**Comment by patvdleer** [comment] 2020-03-19 18:09
same here,

I added `fahclient` to the video group and created `/etc/profile.d/rocm.sh`
```sh
export LD_LIBRARY_PATH=/opt/rocm-3.1.0/opencl/lib/x86_64:/opt/rocm-3.1.0/hsa/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/opt/rocm/bin:/opt/rocm-3.1.0/opencl/bin/x86_64:/opt/rocm-3.1.0/bin:/opt/rocm-3.1.0/opencl/rocprofiler/bin
```

**Comment by seesturm** [comment] 2020-03-19 19:27
I'm also affected. dmesg output is:
```
[175611.038424] amdgpu 0000:0d:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32787, for process FahCore_22 pid 75389 thread FahCore_22 pid 75389)
[175611.038429] amdgpu 0000:0d:00.0:   in page starting at address 0x00007f2c72208000 from client 27
[175611.038431] amdgpu 0000:0d:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00801031
[175611.038433] amdgpu 0000:0d:00.0: 	 MORE_FAULTS: 0x1
[175611.038434] amdgpu 0000:0d:00.0: 	 WALKER_ERROR: 0x0
[175611.038436] amdgpu 0000:0d:00.0: 	 PERMISSION_FAULTS: 0x3
[175611.038437] amdgpu 0000:0d:00.0: 	 MAPPING_ERROR: 0x0
[175611.038438] amdgpu 0000:0d:00.0: 	 RW: 0x0
```

**Comment by patvdleer** [comment] 2020-03-20 12:21
I managed to get it to at least load but sadly that's when the `BAD_WORK_UNIT` kicks in; https://github.com/RadeonOpenCompute/ROCm/issues/1040#issuecomment-601650755

**Comment by barolo** [comment] 2020-03-27 19:52
Just tried it, same issues as above unfortunately

**Comment by patvdleer** [comment] 2020-04-07 11:47
I just upgraded to ROCM 3.3 which now actually works, no more `BAD_WORK_UNIT`!

**Comment by akostadinov** [comment] 2020-04-07 15:23
Same here, looks like issue finally fixed.

**Comment by soulhunter** [comment] 2020-06-05 20:53
I can also confirm this is working on newer versions.  I have Vega FE and RX 580: both cards are working fine with Folding@Home now.

**Comment by DaDummy** [comment] 2020-06-08 15:29
I can confirm this was working correctly for my RX 580 after manually updating the GPU.txt for FAH, but broke again with the latest ROCm update released a couple of days ago.

**Comment by DaDummy** [comment] 2020-06-08 16:11
Putting this into `/etc/profile.d/rocm.sh` and uninstalling the `clinfo` package seem to have helped:

```
export PATH="$PATH:/opt/rocm-3.5.0/bin/:/opt/rocm-3.5.0/opencl/bin/"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/rocm-3.5.0/opencl/lib/"
```

Is there any chance the ROCm OpenCL-only installation packages could be adjusted to create a symlink `/opt/rocm` pointing at the version-specific subfolder so I won't have to keep updating that file whenever the version string changes?

According to the documentation this symlink is already being created  in full installs by some package but that does not seem to be one of those listed at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#performing-an-opencl-only-installation-of-rocm

**Comment by streamhsa** [comment] 2020-06-09 04:15
Hi @DaDummy,
Yes, as you found, soft link to /opt/rocm will be created by rocm-dev component.
As OpenCL-only ROCm does not deal with rocm-dev, soft link will not be created. We need to manually create soft link, if we wish to.

**Comment by rkothako** [comment] 2020-06-09 04:18
Hi @DaDummy,
Yes, as you found, soft link to /opt/rocm will be created by rocm-dev component.
As OpenCL-only ROCm does not deal with rocm-dev, soft link will not be created. We need to manually create soft link, if we wish to.

**Comment by ROCmSupport** [comment] 2021-01-07 10:03
Thank you all for the updates.
As this issue is fixed and no more observed with newer versions, am closing this.
Request to open a new issue if found any.
Thank you.

**Closed by ROCmSupport** 2021-01-07 10:03 UTC
