### ISSUE TITLE
Q: how to build ROCm OpenCL for kernel 4.18

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#513] opened 2018-08-24 11:41 UTC
I would like to try OpenCL on kernel 4.18 on Ubuntu 18.04. I have this plan:

1. checkout master branch of rock-dkms, compile and install.
2. install these pre-built packages:
Setting up hsa-ext-rocr-dev (1.1.8-15-ge851b7a) ...
Setting up hsakmt-roct (1.0.8-1-ge3dd067) ...
Setting up hsakmt-roct-dev (1.0.8-1-ge3dd067) ...
Setting up hsa-rocr-dev (1.1.8-15-ge851b7a) ...
Setting up rocm-opencl (1.2.0-2018071109) ...

Would it work? what do I need to do differently?
thanks

**Comment by gstoner** [comment] 2018-08-24 13:38
There are changes in the Thunk layer to simplify swapping upstream kernel driver,  It not that far our for 1.9 to release weeks, I would wait for this update

**Comment by evgeniyosipov** [comment] 2018-08-24 14:29
**gstoner**
It's will be brilliant, thank you.

**Comment by Moading** [comment] 2018-08-24 18:08
@gstoner 
will 1.9 include opencl device side enqueue? For clarification, when can we expect the release of 1.9?

**Comment by cryptomilk** [comment] 2018-08-28 09:55
I have ROCm OpenCL working with Linux Kernel 4.18 on openSUSE Tumbleweed, I've just installed the RHEL7 RPMs.

```
hsa-rocr-dev-1.1.8-15-ge851b7a-Linux.rpm
hsakmt-roct-1.0.8-1-ge3dd067-Linux.rpm
rocm-opencl-1.2.0-2018071635.x86_64.rpm
rocm-opencl-devel-1.2.0-2018071635.x86_64.rpm
```

**Comment by rkothako** [comment] 2018-08-31 04:01
Hi @Moading 
Device enqueues will be part of 2.0

**Comment by cryptomilk** [comment] 2018-08-31 05:30
Sorry, I was wrong, it doesn't work with Kernel 4.18 and the RHEL RPMs :-(

**Comment by jlgreathouse** [comment] 2018-09-15 22:14
Hi @preda 

With the release of ROCm 1.9 yesterday, you may be able to do what you want. It looks like a user over at Phoronix [has ROCm working under a custom 4.18 kernel](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1047471-amd-rocm-1-9-available-with-vega-20-support-plus-upstream-kernel-compatibility/page2). This user shows directions as well.

**Comment by shimmervoid** [comment] 2018-09-15 23:38
The information provided here is invaluable. I can confirm this works. Thanks @jlgreathouse & perpetually high from phoronix

**Comment by jlgreathouse** [comment] 2018-12-24 21:39
Hi @preda 

If you're interested, I have updated the ROCm [README](https://github.com/RadeonOpenCompute/ROCm/blob/roc-2.0.0/README.md), [website](https://rocm.github.io/ROCmInstall.html), and [documentation](https://rocm-documentation.readthedocs.io/en/latest/Installation_Guide/Installation-Guide.html) to better address your questions.

In particular:

- [This section](https://github.com/RadeonOpenCompute/ROCm/tree/roc-2.0.0#rocm-support-in-upstream-linux-kernels) should better explain the tradeoffs between using the upstream kernel driver and the `rock-dkms` driver module supplied as part of the ROCm repository.
- [This section](https://github.com/RadeonOpenCompute/ROCm/tree/roc-2.0.0#rocm-binary-package-structure) should explain the binary packages, what software they provide, and their dependencies.
- [This section](https://github.com/RadeonOpenCompute/ROCm/tree/roc-2.0.0#performing-an-opencl-only-installation-of-rocm) describes how to install only ROCm OpenCL and its required dependencies along with the kernel driver.
- [This section](https://github.com/RadeonOpenCompute/ROCm/tree/roc-2.0.0#using-debian-based-rocm-with-upstream-kernel-drivers) describes how to install the ROCm user-space software on Ubuntu when you want to use an upstream driver.

Note that I don't explicitly have a section that describes installing just ROCm OpenCL without the kernel driver, but the above information should hopefully allow you to understand how this all fits together and install just the packages you need for that.

I would like to avoid trying to document how to install every permutation of all software offered by ROCm, to prevent our README file from becoming a novel.

In addition, if you are interested in compiling any of your own ROCm software, please feel free to see our [Experimental ROC](https://github.com/RadeonOpenCompute/Experimental_ROC) project, which includes tools and scripts that show how to build all of the ROCm packages from source.

**Closed by jlgreathouse** 2018-12-24 21:39 UTC
Labels: Feature Request
