### ISSUE TITLE
ROCm 4.1.1 OpenCL slowdown vs. ROCm 3.3.0 in gpuowl

### ISSUE THREAD

**Issue by preda** [RadeonOpenCompute/ROCm#1461] opened 2021-04-26 08:39 UTC
Using gpuowl, on Linux 20.04 kernel 5.4.0, Radeon VII,

I have prepared ISA dumps compiled with rocm-opencl3.3.0 vs. rocm-opencl4.1.1, and a summary delta. The conclusion is that a 3% - 4% slowdown is observed in ROCm4.1.1. The occupancy of the critical kernels (carryFused, tailFusedSquare) is decreased, due to the number of VGPRs used.

In the delta below, left is 3.3.0 and right is 4.1.1

[delta.txt](https://github.com/RadeonOpenCompute/ROCm/files/6375493/delta.txt)
[isa3.3.0.txt](https://github.com/RadeonOpenCompute/ROCm/files/6375494/isa3.3.0.txt)
[isa4.1.1.txt](https://github.com/RadeonOpenCompute/ROCm/files/6375495/isa4.1.1.txt)

**Comment by ROCmSupport** [comment] 2021-04-26 09:16
Hi @preda 
Thanks for reaching out.
There is an active ticket already logged #1196 and its a regression between 3.3 and 3.5 and the same is there with 4.0 and 4.1 also.
So I wish to mark this as duplicate of #1196 
Hope it helps.
Thank you.

**Closed** 2021-04-26 09:33 UTC

**Comment by preda** [comment] 2021-04-26 09:45
Yep dup is appropriate.
