### ISSUE TITLE
Different results of CUDA/HIP kernels on Nvidia/AMD GPUs

### ISSUE THREAD

**Issue by DTolm** [RadeonOpenCompute/ROCm#1380] opened 2021-02-13 18:49 UTC
Hello,

I have a kernel, that uploads 4096 float2 numbers with 512 threads (each stores 8 numbers) and does some reordering using 32KB of statically allocated shared memory. CUDA version run on Nvidia 1660Ti GPU produces the correct result. HIP version (obtained with hipify) run on AMD MI100 and Radeon VII produces a different result. I attach both kernels and outputs. What can be the issue behind this behavior? Thank you.

[test.zip](https://github.com/RadeonOpenCompute/ROCm/files/5976267/test.zip)

Best regards,
Dmitrii Tolmachev

**Comment by seesturm** [comment] 2021-02-14 12:48
Looks like this is a compiler bug. When compiled without optimization "-O0" outputs appear to be correct.

**Comment by ROCmSupport** [comment] 2021-02-15 06:00
Thanks @DTolm for reaching us.
Most likely its a compiler bug and so reached compiler team for resolution.
Will share an update very soon.
Thank you.

**Comment by ROCmSupport** [comment] 2021-02-25 05:38
Hi @DTolm 
Got an update for you.
This issue is ready-with-the-fix and it is part of 4.1 code.
ROCm 4.1 is very nearby and request you to check there.
Thank you.

**Comment by DTolm** [comment] 2021-04-05 17:08
@ROCmSupport 
Thanks! I have checked ROCm 4.1 and it works. I also understood the issue myself - it was related to the fact that hipDeviceAttributeMaxThreadsPerBlock was reporting 1024 even when the ROCm was configured with 256 max threads. It seems that you have increased that value to 1024 in the last update, but this reduced the number of registers a thread can use before spilling to global memory. Some of my kernels at VkFFT experience a drop in performance from this, so I wanted to ask if it is possible to provide the exact value of registers per thread I need at compile-time to avoid the spilling? __launch_bounds__ doesn't seem to have any impact.
Thank you!
Best regards,
Dmitrii

**Comment by ROCmSupport** [comment] 2021-04-06 06:29
Thanks @DTolm for the update.
I am closing this as the issue is fixed as per your confirmation too.
Thank you.

**Closed by ROCmSupport** 2021-04-06 06:29 UTC

**Comment by DTolm** [comment] 2021-04-06 09:38
@ROCmSupport can you please comment on the other part of my response? Thank you!

**Comment by ROCmSupport** [comment] 2021-04-06 09:59
Hi @DTolm 
I recommend to open a new issue to discuss on that separately.
Thank you.

**Comment by robosina** [comment] 2022-03-19 18:24
> Looks like this is a compiler bug. When compiled without optimization "-O0" outputs appear to be correct.

I have the same issue in my codes, it's working without optimization (`rocm` version is : `5.0.2`)
