### ISSUE TITLE
Poor performance of LuxMark 3.1 HOTEL scene in ROCm 3.8

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/ROCm#1253] opened 2020-10-05 18:31 UTC
ROCm 3.8 on Linux 5.7.6, with upstream amdgpu driver.

LuxMark 3.1 can be downloaded here: https://github.com/LuxCoreRender/LuxMark/releases/download/luxmark_v3.1/luxmark-linux64-v3.1.tar.bz2

I am running a AMD Radeon R9 Fury X (FIJI, gfx803).

To successfully render the bundled HOTEL scene, you might need to disable `-cl-fast-relaxed-math` in luxmark Options menu, otherwise LLVM might crash or the resulting image will be misrednered.

On my Fury X, this scene renders at about 10.38Mrays/s in about 121 seconds, resulting in a score of 1970.

http://luxmark.info/node/8425 - score: 1970  (stock 1050MHz)

rocm-smi shows me temp < 60°C at all time, and 100% GPU load, and SCLK of 1050MHz at all times.

Reruning few times, I got 1970, 1990, 1989.

Enabling `-cl-fast-relaxed-math` increases tracing to 11.43Mrays/s, but the resulting image is incorrect, and GPU does crashes often (GPU fault detected: 147, trying to read from addr 0x0), resulting in program termination. But the increase would be only of about 10%. So by extrapolating about 2190.

Compared this to the same GPU with same clock speeds from Windows users, this is about half the expected performance:

http://luxmark.info/node/1921 - score: 3054
http://luxmark.info/node/147 - score: 3742
http://luxmark.info/node/1449 - score: 3614
http://luxmark.info/node/2507 - score: 3577
http://luxmark.info/node/1086  - score: 4183  (OC 1197MHz)

I also noticed that Windows reports Local memory: 32kiB, but the Linux with ROCm 3.8 says Local memory: 64kiB

[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5329384/clinfo.txt)
[clinfo-rocm.txt](https://github.com/RadeonOpenCompute/ROCm/files/5329385/clinfo-rocm.txt)
[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/5329386/rocminfo.txt)

**Comment by baryluk** [comment] 2020-11-23 17:53
Even worse now with ROCm 3.9.

The Mrays/s figures in the status bar are even lower than in ROCm 3.8.

Without `-cl-fast-relaxed-math` , the test completes with correct image, and score: 1700, which is way lower than previous 1970 with same settings.

With `-cl-fast-relaxed-math` (default in LuxMark v3.1) the tests completes without GPU, LLVM or application crash, but it is incorrectly rendered. Score: 1903. So, less than previous expected 2910.

**Comment by ROCmSupport** [comment] 2020-12-03 12:21
Hi @baryluk 
Can you please try with 3.10.
Thank you.

**Comment by baryluk** [comment] 2020-12-03 22:21
Tested now with ROCm 3.10 and Linux 5.9.9-1 with upstream amdgpu.

I see now "Local Memory: 32 Kbytes". So that is a change. Now it is consistent with Windows. I am not sure if it is correct or not, but at least it is consistent.

As of results in LuxMark v3.1. Well it is worse. 

MRays/s is way higher (unbelievably so), but the end result is wrong, and even worse, and in both modes. (Previously it was at least correct with `-cl-fast-relaxed-math` not enabled).

With `-cl-fast-relaxed-math` enabled (default for LuxMark v3.1), I am getting ~32.3–32.5MRays/s. End score is 30925-31512  (but 499105 pixels (84.62% of all) is wrong).

With `-cl-fast-relaxed-math` disabled, I am getting 31.9–32.1Mrays/s. End score is 31377 (but 499105 pixels (73.42% of all) is wrong).

So, actually I would say this is a regression compared to ROCm 3.9.0.

Even if these MRays/s scores are correctly, which are about 3 times what I have seen before, for some reasons the LuxMark score is about 15 times the previous score, not 5. My guess, it is a bug in LuxMark scoring method. However, it is also possibly that my GPU was not running at 1050MHz all the time in my previous tests. In this runs now, it was at 1050MHz all the time (verified by hwmon entries in sysfs and using `rocm-smi`).

Also, I am not sure why LuxMark says 499105 pixels are different in both runs (with and without `-cl-fast-relaxed-math`), but reports different percentage, despite the size of the image, and total number of pixels being the same.

**Comment by baryluk** [comment] 2020-12-03 22:23
I am sorry.

Please ignore the post I made minute ago. It was using Mesa 20.2.3 Clover / OpenCL 1.1.

**Comment by baryluk** [comment] 2020-12-03 23:16
@ROCmSupport Slight (2.5%) improvement, but not substantial.

ROCm 3.10 , Linux 5.9.9-1, Platform Version: OpenCL 2.0 AMD-APP (3212.0).

Same system (AMD Radeon R9 Fury X, FIJI, GFX8, gfx803). 64 CU, 1050MHz nominal. Water cooled.

Local Memory: 64KBytes reported by OpenCL for this device in `clinfo` and `LuxMark v3.1`. While this is different than Windows or what Mesa Clover reports, I think it might be actually correct, after referencing some AMD documents. FIJI CU appears to have 64KB of LDS memory. Plus 16KB of L1 cache for scalar data, and 32KB of L1 cache for vector data, shared across 4 CUs. That is my guess, and it kind of matches what `rocminfo` is showing too.

HOTEL scene as before.

With `-cl-fast-relaxed-math` (default) , ≈11.3MRays/s, end score: 2159–2171. (519669 different pixels, 88.11% bad pixels. On a different run 519505 different pixels, 88.08% bad pixels)

Without `-cl-fast-relaxed-math`, ≈10.6MRays/s, end score: 2021–2027. (154251 different pixels, 26.15% bad pixels. On a different run 154118 difference pixels, 26.13% bad pixels)

I would say the results slightly (about 2.5%) better than before, but not that much. It is basically the same as before (in ROCm 3.8), and still substantially lower compared to Windows.

GPU core and memory clock frequencies are stable during the run (as confirmed by hwmon files in sysfs and `rocm-smi`).

My results for 3.9 might have been incorrect, due to unstable clocks, because of this kernel / GPU BIOS bug https://gitlab.freedesktop.org/drm/amd/-/issues/936 . I didn't monitor the GPU clocks fully at the time before, so I can't confirm if it was the case.

**Comment by ROCmSupport** [comment] 2020-12-04 09:56
Thanks @baryluk for the update.
As per current resources we have, we are not in a position to validate gfx8 in a full scale like gfx9.
We have limited test coverage on gfx8.
Hence the delay in responding issues specific to gfx8.
Please stay tuned for the more updates.

**Comment by ableeker** [comment] 2020-12-05 13:45
I can confirm this issue on on gfx9, a gfx900 RX Vega 64.

If I enable cl-fast-relaxed-math, I get 15 MRays/sec, and a score of 2882. However, image validation fails with 88.51% incorrectly rendered pixels. The rendered image is visually clearly incorrect as well, very pale, and noisy.

If I disable cl-fast-relaxed-math, I get 14 MRays/sec, and a score of 2695. This time, image validation is successful with 21.44% pixels rendered incorrectly. This time the visual result is correct.

The other 2 scenes, luxball and neumann, render incorrectly as well with cl-fast-relaxed-math enabled, and correctly with this option disabled.

**Comment by baryluk** [comment] 2020-12-06 04:48
> I can confirm this issue with Luxmark 3.1 on a gfx9, a gfx900 RX Vega 64.
> 
> With cl-fast-relaxed-math enabled, I get 15 MRays/sec, and a score of 2882. However, image validation fails with 88.51% incorrectly rendered pixels. The rendered image is visually clearly incorrect as well, very pale, and noisy.
> 
> With cl-fast-relaxed-math disabled, I get 14 MRays/sec, and a score of 2695. This time, image validation is successful with 21.44% pixels rendered incorrectly. The visual result is correct as well.
> 
> The other 2 scenes, luxball and neumann, render incorrectly as well with cl-fast-relaxed-math enabled, and correctly with this option disabled.

HI @ableeker . This bug is specifically about the performance. Can you tell if the results you are gettings are significantly lower than Windows?

For the correctness issues you check the other bug - https://github.com/RadeonOpenCompute/ROCm/issues/1145

**Comment by ableeker** [comment] 2020-12-06 14:31
I see, I didn't make that clear, Windows is much faster. With cl-fast-relaxed-math disabled I'm getting about 35 M/Rays/sec, and a score of 6500.

Interestingly, amdgpu 20.45, which is now using ROCr, shows the same behaviour, cl-fast-relaxed-math needs to be disabled to render correctly, but is as fast as 20.40, which didn't use ROC and rendered correctly, and Windows.

**Comment by perestoronin** [comment] 2020-12-06 20:47
> ROCm 3.10 , Linux 5.9.9-1, Platform Version: OpenCL 2.0 AMD-APP (3212.0).

please retry with Linux 5.4.81, I have same troubles in degradate performance abount minus 30% with all linux above 5.4*

**Comment by baryluk** [comment] 2020-12-07 08:23
@perestoronin What numbers you are getting on LuxMark 3.1 HOTEL scene? Which GPU.

**Comment by baryluk** [comment] 2020-12-07 08:24
> I see, I didn't make that clear, Windows is much faster. With cl-fast-relaxed-math disabled I'm getting about 35 M/Rays/sec, and a score of 6500.
> 
> Interestingly, amdgpu 20.45, which is now using ROCr, shows the same behaviour, cl-fast-relaxed-math needs to be disabled to render correctly, but is as fast as 20.40, which didn't use ROC and rendered correctly, and Windows.

Thank you. That is super helpful to know!

**Comment by ableeker** [comment] 2020-12-09 18:34
My bad, amdgpu 20.45,that's using ROCr now, is as slow as ROCm, I get 15 MRays/sec, and a score of 2800.

With 20.40, that's not using ROCr, I get 30 MRays/sec, and a score of 5700.

That's with a gfx900, a Vega 64.

**Comment by baryluk** [comment] 2020-12-10 16:11
> My bad, amdgpu-pro 20.45, that's using ROCr now, is as slow as ROCm 3.10, I get 15 MRays/sec, and a score of 2800.
> 
> With amdgpu-pro 20.40, that's NOT using ROCr, I get 30 MRays/sec, and a score of 5700. And I don't have to disable cl-fast-relaxed-math.
> 
> That's with a gfx900, a Vega 64.

That is interesting. Unfortunately I can't install amdgpu-pro 20.40 on my system. amdgpu module fails to compile with kernel 5.9.9 and 5.9.11 that I have on my Debian testing machine.

I will try the non-pro version later, once I clean up the mess.

**Comment by baryluk** [comment] 2020-12-10 18:53
Ok. I managed to test the opencl driver from amdgpu-pro 20.40, but forcing it to install and ignore some dependencies, and configuring paths. It actually worked with upstream amdgpu kernel driver from Linux 5.9.9.

Indeed, performance is better with amdgpu-pro 20.40!

I also tested 20.45 and performance is almost the same as 20.45, only slightly lower.

| Driver           | AMD-APP | Kernel | Local Memory |                 Options |     MRays/s | Score | Bad pixels          |
|------------------|---------|-------:|-------------:|-------------------------|------------:|------:|--------------------:|
| ROCm 3.8         |  3186.0 | 5.7.6  |        64KiB | `-cl-fast-relaxed-math` |      ≈11.43 | ≈2190 |     crash           |
| ROCm 3.8         |  3186.0 | 5.7.6  |        64KiB |                         |      ≈10.38 |  1970 |     pass            |
| ROCm 3.8         |  3186.0 | 5.7.6  |        64KiB |                         |      ≈10.38 |  1990 |     pass            |
| ROCm 3.8         |         | 5.7.6  |        64KiB |                         |      ≈10.38 |  1989 |     pass            |
| ROCm 3.9         |         | 5.7.6  |        64KiB | `-cl-fast-relaxed-math` |             |  1903 |     pass            |
| ROCm 3.9         |         | 5.7.6  |        64KiB |                         |             |  1700 |     pass            |
| ROCm 3.10        |         | 5.9.9  |        64KiB | `-cl-fast-relaxed-math` |       ≈11.3 |  2171 | !!! 519669 / 88.11% |
| ROCm 3.10        |         | 5.9.9  |        64KiB | `-cl-fast-relaxed-math` |       ≈11.3 |  2159 | !!! 519505 / 88.08% |
| ROCm 3.10        |         | 5.9.9  |        64KiB |                         |       ≈10.6 |  2027 |     154251 / 25.13% |
| ROCm 3.10        |         | 5.9.9  |        64KiB |                         |       ≈10.6 |  2021 |     154118 / 26.13% |
| amdgpu-pro 20.45 |  3180.7 | 5.9.9  |        32KiB | `-cl-fast-relaxed-math` |      ≈19.26 |  3663 |     112859 / 19.31% |
| amdgpu-pro 20.45 |  3180.7 | 5.9.9  |        32KiB | `-cl-fast-relaxed-math` | 19.29–19.31 |  3664 |     112973 / 19.15% |
| amdgpu-pro 20.45 |  3180.7 | 5.9.9  |        32KiB |                         |      ≈19.91 |  3798 |     110243 / 18.69% |
| amdgpu-pro 20.40 |  3188.4 | 5.9.9  |        32KiB | `-cl-fast-relaxed-math` | 19.29–19.31 |  3682 |     111620 / 18.92% |
| amdgpu-pro 20.40 |  3188.4 | 5.9.9  |        32KiB |                         | 20.09–20.11 |  3869 |     108931 / 18.47% |
| amdgpu-pro 20.40 |  3188.4 | 5.9.9  |        32KiB |   `-cl-strict-aliasing` | 20.07-20.10 |  3873 |     108832 / 18.45% |



Yes, the result WITHOUT `-cl-fast-relaxed-math` is actually faster! Strange.

And yes, all results 3663 - 3798, are higher than any reported Windows results from the luxmark website (3742). Wonderful.

Now question is, why the ROCm shows so worse performance. And why amdgpu-pro 20.45 for some also shows worse performance.

It looks it might be due to the Local memory reporting. The amdgpu-pro 20.40 reports 32KBytes, just like Windows. The ROCm reports 64KBytes, which feels wrong. But it could be also something else, like actual generated code.

**Comment by ableeker** [comment] 2020-12-11 00:11
I only need OpenCL, so I can install only the OpenCL part from amdgpu 20.40 without kernel module like so:

`amdgpu-install --headless --no-dkms --opencl=pal`

That `--no-dkms` will make sure dkms isn't used.

You should be able to install 20.45 in a similar way, like so:

`amdgpu-install --headless --no-dkms --opencl=rocr`

But it isn't not working with 20.45, that is, it's ignoring `--no-dkms`, and will still try to compile a kernel module, and will fail after a bit. In my cast that's because I'm running Ubuntu 20.10 with kernel 5.8. However, if I then just remove amdgpu-dkms, OpenCL will still work.

**Comment by ableeker** [comment] 2020-12-11 00:14
I believe amdgpu 20.45 is doing much worse than 20.40, because 20.45 is now using ROC as well, while 20.40 didn't.

ROCr, the runtime of ROC, is actually a new feature of 20.40.

**Comment by baryluk** [comment] 2020-12-11 12:11
> I believe amdgpu 20.45 is doing much worse than 20.40, because 20.45 is now using ROC as well, while 20.40 didn't.
> 
> ROCr, the runtime of ROC, is actually a new feature of 20.45.

Fair, but as I said, the amdgpu-pro 20.45 is not slower for me on AMD Radeon RX Fury X (FIJI, gfx803). It looks GPU dependent.

**Comment by amartincolby** [comment] 2020-12-12 21:47
I'm working through similar issues as those mentioned here right now. I have a Vega Frontier Edition Air. I'm running Ubuntu 20.04 with the 5.4.0-58-generic kernel because I had previously been trying to get the proprietary drivers to work. Performance of the Luxball and Neumann are as expected: ~26k for Luxball, ~17.5k for Neumann. The Hotel Lobby, though, is half of what it should be at ~2.3k. The problems with the `dkms` flag being ignored has been noted on other boards as well, @ableeker. I am completely unable to get the proprietary drivers working, so ROCm is my only hope at the moment.

**Comment by baryluk** [comment] 2020-12-12 22:54
@amartincolby It is possible to get OpenCL stuff from amdgpu-pro, without using dkms. It just requires a bit of force: First install amdgpu (non-pro), then: `sudo dpkg --ignore-depends=amdgpu-dkms -i opencl-amdgpu-pro_20.40-1147286_amd64.deb  opencl-orca-amdgpu-pro-icd_20.40-1147286_amd64.deb clinfo-amdgpu-pro_20.40-1147286_amd64.deb opencl-amdgpu-pro-icd_20.40-1147286_amd64.deb` ;)  

Or something like that.

Works for me essentially.

This is how I managed to test amdgpu-pro OpenCL stuff with standard upstream amdgpu driver.

**Comment by amartincolby** [comment] 2020-12-14 02:58
@baryluk When you say non-pro, do you mean the Vega consumer driver package, like Vega 64 instead of Vega Frontier?

**Comment by baryluk** [comment] 2020-12-14 06:58
> @baryluk When you say non-pro, do you mean the Vega consumer driver package, like Vega 64 instead of Vega Frontier?

Check here https://amdgpu-install.readthedocs.io/en/latest/install-script.html

Basically non-pro is AMD driver which is open source, and uses upstream amdgpu driver. (Actually it is based on Mesa).

The pro dirver, has some components that are not open source AFAIK.

Both pro and non-pro drivers are in the same package, you just choose what you want to install.

In general you shouldn't use them, and stick to Mesa, unless you have good reasons too. Testing and using OpenCL is a good reason to try them.

**Comment by amartincolby** [comment] 2020-12-15 03:50
@baryluk So there is no difference? The driver package that I downloaded has the base script, `amdgpu-install`, but it specifically states that unless I select headless installation, it will install pro support, and as such it fails every time. But even if I select headless, it tries to install `amdgpu-pro-pin`, which fails the OS check.

**Comment by baryluk** [comment] 2020-12-15 11:34
> @baryluk So there is no difference? The driver package that I downloaded has the base script, `amdgpu-install`, but it specifically states that unless I select headless installation, it will install pro support, and as such it fails every time. But even if I select headless, it tries to install `amdgpu-pro-pin`, which fails the OS check.

`./amdgpu-install --no-dkms`

This will install non-pro version. To install pro you also need to pass `--pro`.

Once you install non-pro version, you should be able to force install some debs, to get OpenCL. It is ugly, and I don't recommend it long term, but it works. Another way for it not complain is to create fake `amdgpu-dkms` package that will convince the pro driver that it is installed. If you need one, I can make such package.

**Comment by amartincolby** [comment] 2020-12-17 02:52
Honestly, I would be fine with the performance regression for now if Blender worked, which is what I am ultimately interested in. Sadly, Blender is also completely broken, as can be seen in connected issues #1210, #1106, and even older yet still open like #772. I understand that priorities are hard to manage, especially when dealing with software of such complexity, but AMD has long pushed the OpenCL performance of their cards as a selling point, and people who use a lot of OpenCL are much more likely to be using Linux. For gaming drivers, alright. Probably 1% of gamers use Linux, whereas 97% use Windows. I can appreciate focusing on Windows. But workstation demographics are probably 25% Linux or more. That's a huge hunk of users.

Thank you for the offer of the package, but I guess I will wait until they release the pro version of their drivers for Ubuntu 20. Hopefully I'll be able to go completely open source on my driver stack next year.

**Comment by baryluk** [comment] 2020-12-26 03:02
@amartincolby This bug is about LuxMark 3.1 HOTEL scene in ROCm. For other issue, please open separate issue. Would be good to remove off-topic comments. Thanks in advance.

**Comment by amartincolby** [comment] 2020-12-26 03:05
@baryluk I wasn't intending that to be a report about Blender performance, only to reference OpenCL rendering in general. That was me attempting to express understanding with the difficulties of software development while also indicating my disappointment with OpenCL performance and stability.

**Comment by baryluk** [comment] 2020-12-26 03:06
> @baryluk I wasn't intending that to be a report about Blender performance, only to reference OpenCL rendering in general. That was me attempting to express understanding with the difficulties of software development while also indicating my disappointment with OpenCL performance and stability.

That is pointless and derails the discussion. Let's try to make the job of ROCm devs as easy as possible instead.

**Comment by amartincolby** [comment] 2020-12-26 03:47
@baryluk I disagree that it is pointless. I am a consumer of this product. I am offering my reports on it.

**Comment by ROCmSupport** [comment] 2021-01-04 08:31
AMD ROCm dropped supporting gfx8 officially from ROCm 4.0 as per https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support.
Hence closing this issue.
Thank you.

**Closed by ROCmSupport** 2021-01-04 08:31 UTC

**Comment by baryluk** [comment] 2021-01-04 11:19
@ROCmSupport How long is GFX9 going to be supported? Where is the support roadmap / policy?

**Comment by xuhuisheng** [comment] 2021-01-04 11:51
@baryluk 
Maybe the lifecyle of gfx9 is longer. CDNA - aka MI100, gfx908 is GFX9 family series. GCN with 64 wavefront is more suitable for computation. But ROCm team is leak of testing resources.

Not long times before, people said AMD wont support gaming card like navi10, because ROCm will only support computing card like MI100. But AMD shows good news about there is a supporting plan on 2021 for navi. Now, I am total cannot understand the future plan of ROCm.

**Comment by xuhuisheng** [comment] 2021-01-04 12:00
@baryluk 
BTW, I am curious one thing, did you met the gfx803 problems on gfx803 after ROCm-3.7, I noticed you are using fury X - fiji which have 64 cu.
My card RX580 Polaris10 only have 36 cu. I want to find out if the difference of cu number caused the problem of gfx803 issues.
If you have time, could you try this samples on tensorflow? thank you.

```
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

X = tf.fill((300, 5), 5)
Y = tf.fill((300, 5), 10)

model = tf.keras.Sequential()
model.add(Dense(5))
model.compile(optimizer='adam', loss='mse', metrics=['mse'])

epochs = 150
batch_size = 32

print("Fitt...")
#with tf.device('/CPU:0'):#To test on GPU
model.fit(X, Y, batch_size=batch_size, epochs=epochs)

print("Evaluate...")
model.evaluate(X, Y)

print("Predict...")
result = model.predict(tf.fill((1, 5), 5))
print(result)

```

**Comment by ROCmSupport** [comment] 2021-01-04 12:06
Hi @baryluk 
I can not talk about gfx9 long term plans at this moment.
Thank you.

**Comment by baryluk** [comment] 2021-01-04 16:14
> Hi @baryluk
> I can not talk about gfx9 long term plans at this moment.
> Thank you.

Is there any AMD manufactured GPU that I can buy, and have it supported by ROCm for next 5 years?

**Comment by amartincolby** [comment] 2021-01-05 01:50
This is disappointing. AMD is still selling professional-grade gfx8 cards on their website.

**Comment by ROCmSupport** [comment] 2021-01-05 03:54
> 
> 
> > Hi @baryluk
> > I can not talk about gfx9 long term plans at this moment.
> > Thank you.
> 
> Is there any AMD manufactured GPU that I can buy, and have it supported by ROCm for next 5 years?

If its possible for you, I recommend you to buy an MI100.

**Comment by xuhuisheng** [comment] 2021-01-05 04:10
The price of MI100 is $7,377.27. I dont think it suitable for individual customer. Maybe it is just a joke.
http://www.shopblt.com/cgi-bin/shop/shop.cgi?action=thispage&thispage=011004001501_B8ND723P.shtml
