### ISSUE TITLE
Error during installation of rock-dkms 4.0

### ISSUE THREAD

**Issue by gggh000** [RadeonOpenCompute/ROCm#1368] opened 2021-01-25 19:10 UTC
I am re-creating another isntance of this ticket: 
https://github.com/RadeonOpenCompute/ROCm/issues/1367
This ticket was closed by ROCM support without resolving? Why did you close it?
Please refer to issue 1367 to resolve this ticket!!

**Comment by xuhuisheng** [comment] 2021-01-25 23:47
@gggh000 
I have no privileges to close others issues. The #1367 is closed by ROCmSupport who I believe is ROCm supporting team from AMD. 

I am just a customer who bought a RX580, which is dropped official support from ROCm-4.0.

I had met the same rock-dkms issues on linux-5.8 just like you. https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/issues/107 . And @kentrussell said they are woriking on it. He just closed my issue by ROCm-4.0 announced only support linux-5.4 and linux-5.6, not 5.8.

**Comment by gggh000** [comment] 2021-01-26 08:04
i edited then.

**Comment by kentrussell** [comment] 2021-01-26 12:57
Closing this as a duplicate of https://github.com/RadeonOpenCompute/ROCm/issues/1367 , which I reopened (and edited the title accordingly)

**Closed by kentrussell** 2021-01-26 12:57 UTC
