### ISSUE TITLE
HIP_VISIBLE_DEVICES not working properly in ROCm 3.5

### ISSUE THREAD

**Issue by MarcelSimon** [RadeonOpenCompute/ROCm#1170] opened 2020-06-30 08:39 UTC
It seems that neither HIP_VISIBLE_DEVICES nor ROCR_VISIBLE_DEVICE is working properly anymore in ROCm 3.5 and newer. When running a program with 

```
HIP_VISIBLE_DEVICES= python training.py
```

all GPUs are used. The expected behavior is that all GPUs are hidden.

I tested this with Tensorflow version 2.2.

OS: Ubuntu 18.04.4
ROCm version: 3.5.1, using the rocm-dkms package

**Comment by jlgreathouse** [comment] 2020-12-01 04:22
Thanks for the report on this. I just tested this on a ROCm 3.7 system I have sitting around, and I believe this is fixed as of at least ROCm 3.7 (maybe 3.6 as well).

**Closed by jlgreathouse** 2020-12-01 04:22 UTC
Labels: Bug_Functional_Issue

**Comment by jedbrown** [comment] 2022-10-18 23:16
It looks like this is back. Testing on rocm-5.2, I observe that `HIP_VISIBLE_DEVICES= ./app` behaves the same as when the variable is unset, so using all devices. `ROCR_VISIBLE_DEVICES= ./app` finds no device as intended.

**Comment by saadrahim** [comment] 2022-10-18 23:18
Can you file a new ticket?

**Comment by Jacobfaib** [comment] 2022-10-18 23:22
I created one over in the HIP repo a few days ago: https://github.com/ROCm-Developer-Tools/HIP/issues/3001

**Comment by saadrahim** [comment] 2022-10-18 23:23
Thanks, I triaged your issue.
