### ISSUE TITLE
Is ROCm supporting Radeon VII?

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/ROCm#754] opened 2019-04-02 11:09 UTC
Seems like the ROCm performance on Radeon VII is even worse than Vega 64.

Is ROCm WELL supporting Radeon VII?
What kernel version/driver is needed (e.g. Linux image 5.0) ?

Thanks!

**Comment by briansp2020** [comment] 2019-04-02 12:33
_> Seems like the ROCm performance on Radeon VII is even worse than Vega 64._

What makes you say that? People are reporting pretty good performance using Radeon VII and TensorFlow.
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/173#issuecomment-466230523

**Comment by ghostplant** [comment] 2019-04-02 12:36
@briansp2020 Seems like Ubuntu 16.04 doesn't even detect the correct vendor name for this model.
Should I update to a new kernel?

```sh
$ lspci | grep VGA
root@amdgpu:~/gfx-client/onnx_rocmrt_docker# lspci | grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 66af (rev c1)
```

**Comment by Hycdog** [comment] 2019-04-02 12:40
As far as I know, Ubuntu 16.04 LTS with kernel 4.18.0 isn’t working properly with post-Vega cards, and rock-DKMS will fail to build with that kernel. Just update to newer kernel version.You can even try Ubuntu disco with kernel5.0




| |
hyc
邮箱：tubao9hao@126.com
|

Signature is customized by Netease Mail Master

On 04/02/2019 20:36, ghostplant wrote:

@briansp2020 Seems like Ubuntu 16.04 doesn't even detect the correct vendor name for this model.
Should I update to a new kernel?

$ lspci | grep VGA
root@amdgpu:~/gfx-client/onnx_rocmrt_docker# lspci | grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 66af (rev c1)

**Comment by ghostplant** [comment] 2019-04-02 12:42
@Hycdog Thanks, if I install linux-image-5.0, should I purge the installation of `rock-dkms`?

**Comment by Hycdog** [comment] 2019-04-02 12:54
You may check out the full installation document here:
https://github.com/RadeonOpenCompute/ROCm

These meta-packages are not required but may be useful to make it easier to install ROCm on most systems. Some users may want to skip certain packages. For instance, a user that wants to use the upstream kernel drivers (rather than those supplied by AMD) may want to skip the `rocm-dkms` and `rock-dkms` packages, and instead directly install `rocm-dev`.

So yes, if the kernel driver can detect your card correctly, you should directly install `rocm-dev` and follow the steps afterwards.

**Comment by ghostplant** [comment] 2019-04-02 14:12
@Hycdog Hi, I upgrade my Ubuntu to use `Linux amdgpu 5.0.0-8-generic #9-Ubuntu SMP Tue Mar 12 21:58:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`, and also install the latest rocm-dev via apt-get. But rocminfo couldn't detect it, and hip applications failed to run as well:
```sh
root@amdgpu:~# uname -a
Linux amdgpu 5.0.0-8-generic #9-Ubuntu SMP Tue Mar 12 21:58:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
root@amdgpu:~# apt policy rocm-dev
rocm-dev:
  Installed: 2.2.31
  Candidate: 2.2.31
  Version table:
 *** 2.2.31 500
        500 http://repo.radeon.com/rocm/apt/debian xenial/main amd64 Packages
        100 /var/lib/dpkg/status
root@amdgpu:~# lsmod | grep amdgpu
amdgpu               3534848  0
chash                  16384  1 amdgpu
amd_iommu_v2           20480  1 amdgpu
gpu_sched              32768  1 amdgpu
i2c_algo_bit           16384  1 amdgpu
ttm                   102400  1 amdgpu
drm_kms_helper        180224  1 amdgpu
drm                   479232  4 gpu_sched,drm_kms_helper,amdgpu,ttm
root@amdgpu:~# lspci | grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 66af (rev c1)
root@amdgpu:~# /opt/rocm/bin/rocminfo
hsa api call failure at line 900, file: /data/jenkins_workspace/compute-rocm-rel-2.2/rocminfo/rocminfo.cc. Call returned 4104
```

**Comment by ghostplant** [comment] 2019-04-02 14:35
Note that after upgrading Linux kernel to 5.0, this device file `/dev/dri` is missing, even through amdgpu could be found by `lsmod | grep amdgpu`.

**Comment by Hycdog** [comment] 2019-04-02 15:31
Did you reboot your system after installing rocm-dev？




| |
hyc
邮箱：tubao9hao@126.com
|

Signature is customized by Netease Mail Master

On 04/02/2019 22:35, ghostplant wrote:

Note that after upgrading Linux kernel to 5.0, this device file /dev/dri is missing, even through amdgpu could be found by lsmod | grep amdgpu.

**Comment by ghostplant** [comment] 2019-04-02 15:37
@Hycdog Yes, it works just now by upgrading linux-firmware as well. However, even if I uses Linux 5.0 + rocm-dev 2.2, the benchmark is still around 30%-40% worse than Vega64, any explanations or root-causes? Radeon VII should have 10% more TFlops than Vega 64.

**Comment by Hycdog** [comment] 2019-04-02 15:42
@ghostplant 

> @Hycdog Yes, it works just now by upgrading linux-firmware as well. However, even if I uses Linux 5.0 + rocm-dev 2.2, the benchmark is still around 30%-40% worse than Vega64, any explanations or root-causes? Radeon VII should have 10% more TFlops than Vega 64.

I’m not sure ,but maybe you can check out
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/173
for some performance comparison?

**Comment by sebpuetz** [comment] 2019-04-02 16:49
Upstream drivers come with [quite a drop in performance for Radeon VII.](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/329) Up until the most recent (5.0.5, I believe?), all kernels brought the same performance regression.  If you want a properly working (fast) GPU, you probably have to downgrade to 4.15 and install rocm-dkms.

**Comment by ghostplant** [comment] 2019-04-02 16:58
@sebpuetz Thank you. I have tested both `Ubuntu 16.04 + Linux kernel 4.15 + rock-dkms` and `Ubuntu 16.04 + Linux kernel 5.0` have very bad ROCm performance, so I am afraid that `Ubuntu 18.04 + Linux kernel 4.15 + rock-dkms` could be the same.
Do you think the solution of root-cause is just by using Ubuntu 18.04? It just looks strange.

**Comment by koenigjaeger** [comment] 2019-04-02 19:46
@ghostplant I wanted to ask what did you use to upgrade to the 5.0 kernel? I have been having issues with missing firmware on 18.04 and 18.10 with the 4.18 kernel. And then did you install the whole ROCm stack? Since it only supports <4.18 until ROCm 2.3 I believe.

**Comment by sebpuetz** [comment] 2019-04-02 20:02
> @sebpuetz Thank you. I have tested both `Ubuntu 16.04 + Linux kernel 4.15 + rock-dkms` and `Ubuntu 16.04 + Linux kernel 5.0` have very bad ROCm performance, so I am afraid that `Ubuntu 18.04 + Linux kernel 4.15 + rock-dkms` could be the same.
> Do you think the solution of root-cause is just by using Ubuntu 18.04? It just looks strange.

@ghostplant Never used 16.04, so I can't say much about it

>Edit: I have a radeon vii. I also haven't had firmware issues with Fedora 29 using the 5.0 kernel, however ROCm isn't supported in Fedora beyond 2.0 that is in the repos, so I am looking to use ubuntu for now.

@koenigjaeger What's performance on benchmarks with ROCm 2.0 and the upstream kernel? This issue contains some references
 ROCmSoftwarePlatform/tensorflow-upstream#173

**Comment by koenigjaeger** [comment] 2019-04-02 20:38
@sebpuetz I was never able to get ROCm from github working due to the missing firmware I believe and then in fedora I only had OpenCL from Mesa available. 

Then ROCm version from fedora's repos is only at 2.0 and using clinfo I could only see my ryzen 5 + vega 8 available with OpenCL 1.2 and Vega 20 was once again only using OpenCL 1.1 (so I can't really test any real OpenCL code). I also believe the ROCm in fedoras repos is only a part of and not the whole stack.

**Comment by jlgreathouse** [comment] 2019-04-02 21:04
> @briansp2020 Seems like Ubuntu 16.04 doesn't even detect the correct vendor name for this model.
> Should I update to a new kernel?

`sudo update-pciids` will pull a new PCI ID naming list. the command you ran doesn't really have anything to do with your kernel version.

In any case, it seems that you've taken your performance question over to the `tensorflow-upstream` issue, so I'm going to close this issue.

**Closed by jlgreathouse** 2019-04-02 21:04 UTC

**Comment by ghostplant** [comment] 2019-04-03 06:15
@sebpuetz I upgrade the Ubuntu linux kernel from this site:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.15/

**Comment by koenigjaeger** [comment] 2019-04-03 13:43
@ghostplant Thanks, I'll check that out.
