### ISSUE TITLE
rocm-smi should not require sudo for inspecting current GPU state

### ISSUE THREAD

**Issue by seibert** [RadeonOpenCompute/ROCm#562] opened 2018-09-27 13:17 UTC
The `rocm-smi` tool currently tries to relaunch itself with sudo privileges, even when only trying to display the current GPU state.  Looking at the code, it seems that write access to `/sys` is only needed to modify power profiles, clocks, etc, but the script attempts to relaunch itself with sudo regardless of whether read or write operations need to be performed.  This prevents rocm-smi from being used by normal users who can run GPU code, but also want to monitor the GPU load, temperature, etc.

**Comment by kentrussell** [comment] 2018-10-03 12:34
I have a fix internally to push for 1.9.2 where we don't need sudo to do anything except for setting variables. The issue is what @jlgreathouse said, where trying to get the Power Consumption was only obtainable through debugfs, which requires sudo. I have been able to make a change to read a new sysfs file that reports the value as well, we just have to wait for 1.9.2 to push it out.

**Comment by jlgreathouse** [comment] 2018-12-24 22:47
I believe this was fixed as of ROCm 2.0.0. I just tested `rocm-smi` with no arguments on such a system and it no longer requires a `sudo` password. `rocm-smi --showallinfo` also returns everything without needing `sudo`.

**Closed by jlgreathouse** 2018-12-24 22:47 UTC
