### ISSUE TITLE
Can't install rocm-3.10 on Ubuntu 20.04.1 LTS with kernel 5.4.0-56-generic

### ISSUE THREAD

**Issue by elliottbinder** [RadeonOpenCompute/ROCm#1315] opened 2020-12-02 04:17 UTC
First off, I don't know if this is the appropriate place for this but I first ran into this error when trying to install rocm-3.10. I'm getting a similar error to that [listed here](https://community.amd.com/t5/drivers-software/can-t-install-amdgpu-drivers-on-ubuntu-20-04-1-5-4-0-56-generic/m-p/426676).

I can't install rock-dkms, rocm-dkms, or rocm-dev via apt. Similarly when trying to install the Radeon Software for Linux 20.20 Release using the amdgpu-install script, which tries to install amdgpu-dkms. I run into the same issue of this snippet:

```
...
Setting up amdgpu-dkms (1:5.6.0.15-1098277) ...
Loading new amdgpu-5.6.0.15-1098277 DKMS files...
Building for 5.4.0-56-generic
Building for architecture x86_64
Building initial module for 5.4.0-56-generic
Error! Bad return status for module build on kernel: 5.4.0-56-generic (x86_64)
Consult /var/lib/dkms/amdgpu/5.6.0.15-1098277/build/make.log for more information.
dpkg: error processing package amdgpu-dkms (--configure):
 installed amdgpu-dkms package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of amdgpu:
 amdgpu depends on amdgpu-dkms (= 1:5.6.0.15-1098277); however:
  Package amdgpu-dkms is not configured yet.

dpkg: error processing package amdgpu (--configure):
 dependency problems - leaving unconfigured
...
```

I've attached the make log here: [make.log](https://github.com/RadeonOpenCompute/ROCm/files/5626862/make.log)

It looks like it's complaining about some ‘pci_platform_rom’ function not being defined. I wasn't able to find that function anywhere in the included source files under /var/lib/dkms/amdgpu/source, but I was able to find it under the [ROCK-Kernel repo](https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/blob/36767d92bdfecb49f2c5f112285b483549420267/drivers/pci/rom.c).

If anyone can help me figure out what's wrong here or what I can do to fix it, I would greatly appreciate it.

**Comment by xuhuisheng** [comment] 2020-12-02 04:30
Dumplicate of https://github.com/RadeonOpenCompute/ROCm/issues/1307

**Comment by ROCmSupport** [comment] 2020-12-02 04:41
Hi @elliottbinder 
Thanks for reaching out.
We are able to reproduce this issue locally and working with Kernel team on the fix.
I will update once the fix is available.
Thank you.

**Comment by Dantali0n** [comment] 2020-12-02 07:38
Another ROCm release, another one that is broken flashbacks to 3.9.1~

**Comment by Dantali0n** [comment] 2020-12-02 07:41
[rock-dkms-firmware.0.txt](https://github.com/RadeonOpenCompute/ROCm/files/5627655/rock-dkms-firmware.0.txt)

**Comment by ROCmSupport** [comment] 2020-12-02 08:43
Thanks @Dantali0n 
We are aware of this issue, which is specific to 5.4.0-56, our kernel team is working on the fix.
Thank you.

**Comment by ROCmSupport** [comment] 2020-12-04 05:35
Hi All,
Until the fix is available, we recommend to install ROCm on 5.40-54 kernel or hwe kernels.
Thank you.

**Comment by fgnm** [comment] 2020-12-06 11:59
Using 5.6.0 Kernel fixed the compiling issue, I had to update because even switching to 5.4.0-54 compiling fails.

**Comment by Dantali0n** [comment] 2020-12-07 09:26
> Hi All,
> Until the fix is available, we recommend to install ROCm on 5.4.0-54 kernel or hwe kernels.
> Thank you.

Compilation on kernel 5.4.0-54 fails much the same way as 5.4.0-56, however, 5.4.0-53 works for me.

**Comment by ROCmSupport** [comment] 2020-12-07 09:45
Thanks @Dantali0n 
Strange that ROCm works for me with 5.4.0-54.
Anyway my recommendation is to use any working kernel. Good to know that 5.4.0-53 works.
Thank you.

**Comment by boxerab** [comment] 2020-12-08 21:06
I had a similar issue on ubuntu 20.1 with kernel 5.8, with the same error. Will the upcoming fix address 5.8 ?

**Comment by ROCmSupport** [comment] 2020-12-09 04:33
Hi @boxerab 
Its not clear about Ubuntu version and kernel version from your side.
If you are talking about 20.10, I can say NO as we do not officially support non-LTS versions like 20.10.

**Comment by boxerab** [comment] 2020-12-09 13:35
@ROCmSupport I use 20.10 because my RX 480 freezes when I use 20.04 LTS.  Something to do with amdgpu dc settings, I think.

**Comment by ROCmSupport** [comment] 2020-12-09 13:43
Hi All,
Good news is that fix for this issue is ready, validation is in progress and it will be pushed soon.
Thank you.

**Comment by Silverfox28** [comment] 2020-12-10 10:43
Is the fix ready?

**Comment by ROCmSupport** [comment] 2020-12-10 12:02
Hi @Silverfox28 
Fix is ready, validation is in progress. It will be pushed in a day.

**Comment by ROCmSupport** [comment] 2020-12-11 04:36
Hi @Dantali0n , @boxerab , @elliottbinder , @Silverfox28 
Fix for 5.4.0-56 is ready and pushed too. Updated Documentation accordingly.
Request to try the new packages.

Note: AMD ROCm v3.10 fails to install on Ubuntu kernel v5.4.0-56. To resolve the installation issue, new packages for 'rock-dkms' and 'rock-dkms-firmware' are created and replaced. It is recommended to perform a clean and fresh installation with the new packages.

Thank you.

**Closed by ROCmSupport** 2020-12-11 04:36 UTC

**Comment by advancingu** [comment] 2020-12-12 11:53
@ROCmSupport So someone in the ROCm team honestly replaced already published packages with a different build and did _not_ release a new package version? Why on earth would anyone think this is a good idea? The ROCm team should _really_ work on establishing a better release process.

**Comment by ROCmSupport** [comment] 2020-12-14 06:10
Hi @advancingu 
As per the management decision, we replaced faulty kernel packages with working ones.
This is not always the process, we have defined rules to follow and based on situation, we act accordingly.
This time management discussed and came up with resolution of replacing both kernel packages with fixed ones and so happened.
Hope you got the point.
Thank you.
