### ISSUE TITLE
ROCm programs hangs with Vega 20 (MI 50)

### ISSUE THREAD

**Issue by arfio** [RadeonOpenCompute/ROCm#1386] opened 2021-02-19 15:00 UTC
Hi,

I have recently installed ROCm v4.0.0 on a server running 2 Vega 20 GPUs (MI 50).

The clinfo command locks up like the issues #484 #1326. The difference is I have to force the restart of the server to have access to the agents after the program locks. The bug.tar.gz locks also and the output is in the output.txt file. I thought it was only with OpenCL programs but it happens also with Tensorflow scripts.

The two GPUs are not connected with XGMi. The motherboard uses the latest BIOS available. The issue happened with Ubuntu 18.04 (Linux kernel 4.15) and 20.04 (Linux kernel 5.4.0-65).

[rocminfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/6010742/rocminfo.txt)
[bug.tar.gz](https://github.com/RadeonOpenCompute/ROCm/files/6010743/bug.tar.gz)
[output.txt](https://github.com/RadeonOpenCompute/ROCm/files/6010744/output.txt)
[clinfo.txt](https://github.com/RadeonOpenCompute/ROCm/files/6010745/clinfo.txt)
[dmesg.txt](https://github.com/RadeonOpenCompute/ROCm/files/6010746/dmesg.txt)

**Comment by ROCmSupport** [comment] 2021-02-22 06:16
Thanks @arfio for reaching us.

From the dmesg, looks like severe hardware error observed. Might be hardware problem.
_[ 1358.996458] amdgpu 0000:83:00.0: uncorrectable hardware error(ERREVENT_ATHUB_INTERRUPT) detected!_

I will get more information for you.
Thank you.

**Comment by kentrussell** [comment] 2021-02-23 15:34
I wonder if there might be a hardware failure in there. The dmesg shows that the HW is hanging during GPU reset, the SMU can't be stopped successfully, PowerPlay IP block can't be shut down cleanly, and then getting things restarted again just craps out. Is this isolated to one of the GPUs, or can it be seen on both? And how consistent is it? 
Normally, a UE (Uncorrectable Error) is not going to take the whole thing down, but it is possible in some extreme cases. First, I'd suggest trying to reproduce it with a single GPU in there. If you can reproduce it, swap the GPU and try again. If it only happens on one, it's more likely to be a HW failure, but if it's occurring on both, then there's some deeper digging required. Thanks!

**Comment by ROCmSupport** [comment] 2021-02-26 05:02
Hi @arfio 
Most likely its an hardware issue.
As suggested by Kent, recommend to try plugging one card every time and share an update.
Thank you.

**Comment by arfio** [comment] 2021-02-27 02:50
Hi @ROCmSupport @kentrussell 
After verification by running a sample program on each GPU, we identified that one of the GPU installed was not working correctly, so we will remove and replace the board.
Thank you for your time.

**Comment by ROCmSupport** [comment] 2021-03-01 06:05
Thank you very much @arfio 
I am closing it now then.

**Closed by ROCmSupport** 2021-03-01 06:05 UTC

**Comment by arfio** [comment] 2021-03-11 15:08
Hi @ROCmSupport 

I tested each GPU separately, and they all work. We have the latest BIOS update, latest ROCm installation. We have also tested different slots, but they are all working correctly when we only have one GPU.

We keep having the same issue. We will receive XGMi connectors, and it will maybe solve the issue, but I wanted to let you know that it still isn't working correctly without them.
