### ISSUE TITLE
Could I install the ROCm project from source?

### ISSUE THREAD

**Issue by ShuoleiWang** [RadeonOpenCompute/ROCm#1350] opened 2020-12-29 15:51 UTC
Hi! I want to make some changes in ROCm src, so I want to manually install all necessary components of ROCm from source code. However, I don't know which components are necessary for ROCm and some components don't have install tutorials. In addition, I cannot successfully install some components like HIP, because it shows it lacks some dependencies in CMake step, and I guess it is because I haven't installed some other components in ROCm. Could anyone have met the same problem? or have any experience in installing the whole ROCm project? Thanks!

**Comment by xuhuisheng** [comment] 2020-12-29 23:30
I uploaded some building scripts for ROCm-4.0.
https://github.com/xuhuisheng/rocm-build/

**Comment by ROCmSupport** [comment] 2021-01-04 05:56
Hi @ShuoleiWang 
Thanks for reaching us out.
We are already working on stabilizing the process for building ROCm components smoothly, please stay tuned for the updates.
Thank you.

**Comment by ROCmSupport** [comment] 2021-02-01 07:21
Duplicate of #1188
Request to follow #1188 
Thank you.

**Closed by ROCmSupport** 2021-02-01 07:21 UTC
