### ISSUE TITLE
Create docs/x.y.z branches

### ISSUE THREAD

**Issue by saadrahim** [RadeonOpenCompute/ROCm#2213] opened 2023-06-01 15:57 UTC
For all ROCm releases from 5.0.0 to 5.5.1, create a docs/x.y.z branch.

Also, create the corresponding RTD build jobs.

**Comment by samjwu** [comment] 2023-06-01 16:12
Duplicate of https://github.com/RadeonOpenCompute/ROCm/issues/2212

**Closed by samjwu** 2023-06-01 16:12 UTC
